// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_unifi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func UnifiProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type UnifiModel struct {
}
