// Command openapi-generator-postprocess prepares a split OpenAPI Generator Go
// client by bundling nested model structs and exposing model aliases to the API
// package.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

func main() {
	modelsDir := flag.String("models", "", "directory containing generated model_*.go files")
	mappingsPath := flag.String("mappings", "", "nested model to owner mapping file")
	aliasesPath := flag.String("aliases", "", "output path for generated model aliases")
	aliasPackage := flag.String("alias-package", "", "package name for generated aliases")
	aliasImport := flag.String("alias-import", "", "import path for the models package")
	flag.Parse()

	if *modelsDir == "" || *mappingsPath == "" || *aliasesPath == "" || *aliasPackage == "" || *aliasImport == "" {
		flag.Usage()
		os.Exit(2)
	}

	mappings, err := readMappings(*mappingsPath)
	if err != nil {
		fatal(err)
	}
	if err := bundleModels(*modelsDir, mappings); err != nil {
		fatal(err)
	}
	if err := writeAliases(*modelsDir, *aliasesPath, *aliasPackage, *aliasImport); err != nil {
		fatal(err)
	}
}

func readMappings(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	mappings := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		child, owner, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("%s: invalid mapping %q", path, line)
		}
		mappings[child] = owner
	}
	return mappings, scanner.Err()
}

func bundleModels(dir string, mappings map[string]string) error {
	files, types, err := parseModelFiles(dir)
	if err != nil {
		return err
	}

	owners := map[string][]string{}
	for childType, ownerType := range mappings {
		childPath, childOK := types[childType]
		ownerPath, ownerOK := types[ownerType]
		if !childOK || !ownerOK || childPath == ownerPath {
			continue
		}
		owners[ownerPath] = append(owners[ownerPath], childPath)
	}

	for ownerPath, childPaths := range owners {
		sort.Strings(childPaths)
		seen := map[string]bool{}
		merged := []*ast.File{files[ownerPath]}
		for _, childPath := range childPaths {
			if seen[childPath] {
				continue
			}
			seen[childPath] = true
			merged = append(merged, files[childPath])
		}
		if err := writeMergedFile(ownerPath, merged); err != nil {
			return err
		}
		for childPath := range seen {
			if err := os.Remove(childPath); err != nil {
				return err
			}
		}
	}
	return nil
}

func parseModelFiles(dir string) (map[string]*ast.File, map[string]string, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "model_*.go"))
	if err != nil {
		return nil, nil, err
	}
	files := make(map[string]*ast.File, len(paths))
	types := map[string]string{}
	for _, path := range paths {
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
		if err != nil {
			return nil, nil, err
		}
		files[path] = file
		for _, name := range declaredTypes(file) {
			types[name] = path
		}
	}
	return files, types, nil
}

func declaredTypes(file *ast.File) []string {
	var names []string
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			names = append(names, spec.(*ast.TypeSpec).Name.Name)
		}
	}
	return names
}

func writeMergedFile(path string, files []*ast.File) error {
	merged := &ast.File{Name: ast.NewIdent(files[0].Name.Name)}
	imports := map[string]*ast.ImportSpec{}
	for _, file := range files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if ok && gen.Tok == token.IMPORT {
				for _, spec := range gen.Specs {
					imp := spec.(*ast.ImportSpec)
					key := imp.Path.Value
					if imp.Name != nil {
						key = imp.Name.Name + " " + key
					}
					imports[key] = imp
				}
				continue
			}
			merged.Decls = append(merged.Decls, decl)
		}
	}

	if len(imports) > 0 {
		keys := make([]string, 0, len(imports))
		for key := range imports {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		specs := make([]ast.Spec, 0, len(keys))
		for _, key := range keys {
			specs = append(specs, imports[key])
		}
		merged.Decls = append([]ast.Decl{&ast.GenDecl{Tok: token.IMPORT, Lparen: 1, Specs: specs}}, merged.Decls...)
	}

	var out strings.Builder
	out.WriteString("// Code generated by OpenAPI Generator and bundled by openapi-generator-postprocess; DO NOT EDIT.\n\n")
	if err := format.Node(&out, token.NewFileSet(), merged); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(out.String()), 0o644)
}

func writeAliases(modelsDir, outputPath, packageName, importPath string) error {
	files, _, err := parseModelFiles(modelsDir)
	if err != nil {
		return err
	}

	var names []string
	for _, file := range files {
		for _, name := range declaredTypes(file) {
			if unicode.IsUpper([]rune(name)[0]) {
				names = append(names, name)
			}
		}
	}
	sort.Strings(names)

	var out strings.Builder
	fmt.Fprintln(&out, "// Code generated by openapi-generator-postprocess; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	fmt.Fprintf(&out, "import models %q\n\n", importPath)
	for _, name := range names {
		fmt.Fprintf(&out, "type %s = models.%s\n", name, name)
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(outputPath, formatted, 0o644)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
