package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

// oapiConfig is the oapi-codegen-exp (V3) YAML configuration schema.
// https://github.com/oapi-codegen/oapi-codegen-exp/blob/main/Configuration.md
type oapiConfig struct {
	Package           string         `yaml:"package"`
	Output            string         `yaml:"output"`
	Generation        oapiGeneration `yaml:"generation"`
	OutputOptions     oapiOutputOpts `yaml:"output-options"`
	NameSubstitutions oapiNameSubs   `yaml:"name-substitutions"`
}

type oapiGeneration struct {
	Client bool `yaml:"client"`
}

type oapiOutputOpts struct {
	IncludeTags []string `yaml:"include-tags"`
}

type oapiNameSubs struct {
	TypeNames     map[string]string `yaml:"type-names,omitempty"`
	PropertyNames map[string]string `yaml:"property-names,omitempty"`
}

// WriteOAPICodegenConfigs writes two consolidated oapi-codegen-exp (V3) config
// files — one for all non-settings resources (package unifi) and one for all
// settings resources (package settings).  Each file carries the complete
// name-substitution tables exactly once, eliminating the duplication that
// per-resource configs would cause.
//
// The resulting files are consumed by the static //go:generate directives in
// the repo-root generate.go:
//
//	//go:generate go tool oapi-codegen -config assets/oapi-codegen-exp/unifi.yaml    assets/openapi.yaml
//	//go:generate go tool oapi-codegen -config assets/oapi-codegen-exp/settings.yaml assets/openapi.yaml
func WriteOAPICodegenConfigs(resources []*ResourceInfo, configDir, specPath, clientsDir string) error {
	// ── 1. Build name-substitution tables from resource definitions ───────────

	propertyNames := map[string]string{}
	typeNames := map[string]string{}

	var resourceTags []string
	var settingsTags []string

	for _, r := range resources {
		for typeName := range r.Types {
			typeNames[typeName] = typeName
		}
		for _, t := range r.Types {
			for _, f := range t.Fields {
				if f == nil {
					continue
				}
				// First writer wins — mirrors WriteGeneratorConfig semantics.
				if _, seen := propertyNames[f.JSONName]; !seen {
					propertyNames[f.JSONName] = f.FieldName
				}
			}
		}
		if r.IsSetting() {
			settingsTags = append(settingsTags, r.StructName)
		} else {
			resourceTags = append(resourceTags, r.StructName)
		}
	}

	// NetworkMembersGroup has both "_id" and "id"; keep "_id" → ID and
	// remap plain "id" → Id to avoid duplicate Go field declarations.
	if propertyNames["_id"] == "ID" && propertyNames["id"] == "ID" {
		propertyNames["id"] = "Id"
	}

	sort.Strings(resourceTags)
	sort.Strings(settingsTags)

	// ── 2. Create output directories ──────────────────────────────────────────

	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", configDir, err)
	}

	// ── 3. Write the two consolidated config files ────────────────────────────

	configs := []struct {
		filename string
		cfg      oapiConfig
	}{
		{
			filename: filepath.Join(configDir, "unifi.yaml"),
			cfg: oapiConfig{
				Package: "unifi",
				Output:  filepath.Join(clientsDir, "unifi.gen.go"),
				Generation: oapiGeneration{
					Client: true,
				},
				OutputOptions: oapiOutputOpts{
					IncludeTags: resourceTags,
				},
				NameSubstitutions: oapiNameSubs{
					TypeNames:     typeNames,
					PropertyNames: propertyNames,
				},
			},
		},
		{
			filename: filepath.Join(configDir, "settings.yaml"),
			cfg: oapiConfig{
				Package: "settings",
				Output:  filepath.Join(clientsDir, "settings", "settings.gen.go"),
				Generation: oapiGeneration{
					Client: true,
				},
				OutputOptions: oapiOutputOpts{
					IncludeTags: settingsTags,
				},
				NameSubstitutions: oapiNameSubs{
					TypeNames:     typeNames,
					PropertyNames: propertyNames,
				},
			},
		},
	}

	for _, c := range configs {
		data, err := yaml.Marshal(c.cfg)
		if err != nil {
			return fmt.Errorf("marshal %s: %w", c.filename, err)
		}
		content := append([]byte("# Generated by cmd/fields. DO NOT EDIT.\n"), data...)
		if err := os.WriteFile(c.filename, content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", c.filename, err)
		}
	}

	return nil
}
