// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_user

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_hidden": schema.BoolAttribute{
							Computed: true,
						},
						"attr_hidden_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_no_delete": schema.BoolAttribute{
							Computed: true,
						},
						"attr_no_edit": schema.BoolAttribute{
							Computed: true,
						},
						"blocked": schema.BoolAttribute{
							Computed: true,
						},
						"dev_id_override": schema.Int64Attribute{
							Computed: true,
						},
						"fixed_ap_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"fixed_ap_mac": schema.StringAttribute{
							Computed: true,
						},
						"fixed_ip": schema.StringAttribute{
							Computed: true,
						},
						"hostname": schema.StringAttribute{
							Computed: true,
						},
						"ip": schema.StringAttribute{
							Computed: true,
						},
						"last_seen": schema.Int64Attribute{
							Computed: true,
						},
						"local_dns_record": schema.StringAttribute{
							Computed: true,
						},
						"local_dns_record_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"mac": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"network_id": schema.StringAttribute{
							Computed: true,
						},
						"note": schema.StringAttribute{
							Computed: true,
						},
						"site_id": schema.StringAttribute{
							Computed: true,
						},
						"use_fixedip": schema.BoolAttribute{
							Computed: true,
						},
						"usergroup_id": schema.StringAttribute{
							Computed: true,
						},
						"virtual_network_override_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"virtual_network_override_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"meta": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"msg": schema.StringAttribute{
						Computed: true,
					},
					"rc": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetaType{
					ObjectType: types.ObjectType{
						AttrTypes: MetaValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type UserModel struct {
	Data types.List   `tfsdk:"data"`
	Id   types.String `tfsdk:"id"`
	Meta MetaValue    `tfsdk:"meta"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return nil, diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return nil, diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return nil, diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return nil, diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	blockedAttribute, ok := attributes["blocked"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`blocked is missing from object`)

		return nil, diags
	}

	blockedVal, ok := blockedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`blocked expected to be basetypes.BoolValue, was: %T`, blockedAttribute))
	}

	devIdOverrideAttribute, ok := attributes["dev_id_override"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dev_id_override is missing from object`)

		return nil, diags
	}

	devIdOverrideVal, ok := devIdOverrideAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dev_id_override expected to be basetypes.Int64Value, was: %T`, devIdOverrideAttribute))
	}

	fixedApEnabledAttribute, ok := attributes["fixed_ap_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ap_enabled is missing from object`)

		return nil, diags
	}

	fixedApEnabledVal, ok := fixedApEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ap_enabled expected to be basetypes.BoolValue, was: %T`, fixedApEnabledAttribute))
	}

	fixedApMacAttribute, ok := attributes["fixed_ap_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ap_mac is missing from object`)

		return nil, diags
	}

	fixedApMacVal, ok := fixedApMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ap_mac expected to be basetypes.StringValue, was: %T`, fixedApMacAttribute))
	}

	fixedIpAttribute, ok := attributes["fixed_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ip is missing from object`)

		return nil, diags
	}

	fixedIpVal, ok := fixedIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ip expected to be basetypes.StringValue, was: %T`, fixedIpAttribute))
	}

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return nil, diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return nil, diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	lastSeenAttribute, ok := attributes["last_seen"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_seen is missing from object`)

		return nil, diags
	}

	lastSeenVal, ok := lastSeenAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_seen expected to be basetypes.Int64Value, was: %T`, lastSeenAttribute))
	}

	localDnsRecordAttribute, ok := attributes["local_dns_record"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_dns_record is missing from object`)

		return nil, diags
	}

	localDnsRecordVal, ok := localDnsRecordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_dns_record expected to be basetypes.StringValue, was: %T`, localDnsRecordAttribute))
	}

	localDnsRecordEnabledAttribute, ok := attributes["local_dns_record_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_dns_record_enabled is missing from object`)

		return nil, diags
	}

	localDnsRecordEnabledVal, ok := localDnsRecordEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_dns_record_enabled expected to be basetypes.BoolValue, was: %T`, localDnsRecordEnabledAttribute))
	}

	macAttribute, ok := attributes["mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mac is missing from object`)

		return nil, diags
	}

	macVal, ok := macAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mac expected to be basetypes.StringValue, was: %T`, macAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return nil, diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	noteAttribute, ok := attributes["note"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`note is missing from object`)

		return nil, diags
	}

	noteVal, ok := noteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`note expected to be basetypes.StringValue, was: %T`, noteAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return nil, diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	useFixedipAttribute, ok := attributes["use_fixedip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use_fixedip is missing from object`)

		return nil, diags
	}

	useFixedipVal, ok := useFixedipAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use_fixedip expected to be basetypes.BoolValue, was: %T`, useFixedipAttribute))
	}

	usergroupIdAttribute, ok := attributes["usergroup_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`usergroup_id is missing from object`)

		return nil, diags
	}

	usergroupIdVal, ok := usergroupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`usergroup_id expected to be basetypes.StringValue, was: %T`, usergroupIdAttribute))
	}

	virtualNetworkOverrideEnabledAttribute, ok := attributes["virtual_network_override_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`virtual_network_override_enabled is missing from object`)

		return nil, diags
	}

	virtualNetworkOverrideEnabledVal, ok := virtualNetworkOverrideEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`virtual_network_override_enabled expected to be basetypes.BoolValue, was: %T`, virtualNetworkOverrideEnabledAttribute))
	}

	virtualNetworkOverrideIdAttribute, ok := attributes["virtual_network_override_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`virtual_network_override_id is missing from object`)

		return nil, diags
	}

	virtualNetworkOverrideIdVal, ok := virtualNetworkOverrideIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`virtual_network_override_id expected to be basetypes.StringValue, was: %T`, virtualNetworkOverrideIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Id:                            idVal,
		AttrHidden:                    attrHiddenVal,
		AttrHiddenId:                  attrHiddenIdVal,
		AttrNoDelete:                  attrNoDeleteVal,
		AttrNoEdit:                    attrNoEditVal,
		Blocked:                       blockedVal,
		DevIdOverride:                 devIdOverrideVal,
		FixedApEnabled:                fixedApEnabledVal,
		FixedApMac:                    fixedApMacVal,
		FixedIp:                       fixedIpVal,
		Hostname:                      hostnameVal,
		Ip:                            ipVal,
		LastSeen:                      lastSeenVal,
		LocalDnsRecord:                localDnsRecordVal,
		LocalDnsRecordEnabled:         localDnsRecordEnabledVal,
		Mac:                           macVal,
		Name:                          nameVal,
		NetworkId:                     networkIdVal,
		Note:                          noteVal,
		SiteId:                        siteIdVal,
		UseFixedip:                    useFixedipVal,
		UsergroupId:                   usergroupIdVal,
		VirtualNetworkOverrideEnabled: virtualNetworkOverrideEnabledVal,
		VirtualNetworkOverrideId:      virtualNetworkOverrideIdVal,
		state:                         attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	blockedAttribute, ok := attributes["blocked"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`blocked is missing from object`)

		return NewDataValueUnknown(), diags
	}

	blockedVal, ok := blockedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`blocked expected to be basetypes.BoolValue, was: %T`, blockedAttribute))
	}

	devIdOverrideAttribute, ok := attributes["dev_id_override"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dev_id_override is missing from object`)

		return NewDataValueUnknown(), diags
	}

	devIdOverrideVal, ok := devIdOverrideAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dev_id_override expected to be basetypes.Int64Value, was: %T`, devIdOverrideAttribute))
	}

	fixedApEnabledAttribute, ok := attributes["fixed_ap_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ap_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	fixedApEnabledVal, ok := fixedApEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ap_enabled expected to be basetypes.BoolValue, was: %T`, fixedApEnabledAttribute))
	}

	fixedApMacAttribute, ok := attributes["fixed_ap_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ap_mac is missing from object`)

		return NewDataValueUnknown(), diags
	}

	fixedApMacVal, ok := fixedApMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ap_mac expected to be basetypes.StringValue, was: %T`, fixedApMacAttribute))
	}

	fixedIpAttribute, ok := attributes["fixed_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ip is missing from object`)

		return NewDataValueUnknown(), diags
	}

	fixedIpVal, ok := fixedIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ip expected to be basetypes.StringValue, was: %T`, fixedIpAttribute))
	}

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return NewDataValueUnknown(), diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return NewDataValueUnknown(), diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	lastSeenAttribute, ok := attributes["last_seen"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_seen is missing from object`)

		return NewDataValueUnknown(), diags
	}

	lastSeenVal, ok := lastSeenAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_seen expected to be basetypes.Int64Value, was: %T`, lastSeenAttribute))
	}

	localDnsRecordAttribute, ok := attributes["local_dns_record"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_dns_record is missing from object`)

		return NewDataValueUnknown(), diags
	}

	localDnsRecordVal, ok := localDnsRecordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_dns_record expected to be basetypes.StringValue, was: %T`, localDnsRecordAttribute))
	}

	localDnsRecordEnabledAttribute, ok := attributes["local_dns_record_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_dns_record_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	localDnsRecordEnabledVal, ok := localDnsRecordEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_dns_record_enabled expected to be basetypes.BoolValue, was: %T`, localDnsRecordEnabledAttribute))
	}

	macAttribute, ok := attributes["mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mac is missing from object`)

		return NewDataValueUnknown(), diags
	}

	macVal, ok := macAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mac expected to be basetypes.StringValue, was: %T`, macAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	noteAttribute, ok := attributes["note"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`note is missing from object`)

		return NewDataValueUnknown(), diags
	}

	noteVal, ok := noteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`note expected to be basetypes.StringValue, was: %T`, noteAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	useFixedipAttribute, ok := attributes["use_fixedip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use_fixedip is missing from object`)

		return NewDataValueUnknown(), diags
	}

	useFixedipVal, ok := useFixedipAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use_fixedip expected to be basetypes.BoolValue, was: %T`, useFixedipAttribute))
	}

	usergroupIdAttribute, ok := attributes["usergroup_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`usergroup_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	usergroupIdVal, ok := usergroupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`usergroup_id expected to be basetypes.StringValue, was: %T`, usergroupIdAttribute))
	}

	virtualNetworkOverrideEnabledAttribute, ok := attributes["virtual_network_override_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`virtual_network_override_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	virtualNetworkOverrideEnabledVal, ok := virtualNetworkOverrideEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`virtual_network_override_enabled expected to be basetypes.BoolValue, was: %T`, virtualNetworkOverrideEnabledAttribute))
	}

	virtualNetworkOverrideIdAttribute, ok := attributes["virtual_network_override_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`virtual_network_override_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	virtualNetworkOverrideIdVal, ok := virtualNetworkOverrideIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`virtual_network_override_id expected to be basetypes.StringValue, was: %T`, virtualNetworkOverrideIdAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Id:                            idVal,
		AttrHidden:                    attrHiddenVal,
		AttrHiddenId:                  attrHiddenIdVal,
		AttrNoDelete:                  attrNoDeleteVal,
		AttrNoEdit:                    attrNoEditVal,
		Blocked:                       blockedVal,
		DevIdOverride:                 devIdOverrideVal,
		FixedApEnabled:                fixedApEnabledVal,
		FixedApMac:                    fixedApMacVal,
		FixedIp:                       fixedIpVal,
		Hostname:                      hostnameVal,
		Ip:                            ipVal,
		LastSeen:                      lastSeenVal,
		LocalDnsRecord:                localDnsRecordVal,
		LocalDnsRecordEnabled:         localDnsRecordEnabledVal,
		Mac:                           macVal,
		Name:                          nameVal,
		NetworkId:                     networkIdVal,
		Note:                          noteVal,
		SiteId:                        siteIdVal,
		UseFixedip:                    useFixedipVal,
		UsergroupId:                   usergroupIdVal,
		VirtualNetworkOverrideEnabled: virtualNetworkOverrideEnabledVal,
		VirtualNetworkOverrideId:      virtualNetworkOverrideIdVal,
		state:                         attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Id                            basetypes.StringValue `tfsdk:"_id"`
	AttrHidden                    basetypes.BoolValue   `tfsdk:"attr_hidden"`
	AttrHiddenId                  basetypes.StringValue `tfsdk:"attr_hidden_id"`
	AttrNoDelete                  basetypes.BoolValue   `tfsdk:"attr_no_delete"`
	AttrNoEdit                    basetypes.BoolValue   `tfsdk:"attr_no_edit"`
	Blocked                       basetypes.BoolValue   `tfsdk:"blocked"`
	DevIdOverride                 basetypes.Int64Value  `tfsdk:"dev_id_override"`
	FixedApEnabled                basetypes.BoolValue   `tfsdk:"fixed_ap_enabled"`
	FixedApMac                    basetypes.StringValue `tfsdk:"fixed_ap_mac"`
	FixedIp                       basetypes.StringValue `tfsdk:"fixed_ip"`
	Hostname                      basetypes.StringValue `tfsdk:"hostname"`
	Ip                            basetypes.StringValue `tfsdk:"ip"`
	LastSeen                      basetypes.Int64Value  `tfsdk:"last_seen"`
	LocalDnsRecord                basetypes.StringValue `tfsdk:"local_dns_record"`
	LocalDnsRecordEnabled         basetypes.BoolValue   `tfsdk:"local_dns_record_enabled"`
	Mac                           basetypes.StringValue `tfsdk:"mac"`
	Name                          basetypes.StringValue `tfsdk:"name"`
	NetworkId                     basetypes.StringValue `tfsdk:"network_id"`
	Note                          basetypes.StringValue `tfsdk:"note"`
	SiteId                        basetypes.StringValue `tfsdk:"site_id"`
	UseFixedip                    basetypes.BoolValue   `tfsdk:"use_fixedip"`
	UsergroupId                   basetypes.StringValue `tfsdk:"usergroup_id"`
	VirtualNetworkOverrideEnabled basetypes.BoolValue   `tfsdk:"virtual_network_override_enabled"`
	VirtualNetworkOverrideId      basetypes.StringValue `tfsdk:"virtual_network_override_id"`
	state                         attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 24)

	var val tftypes.Value
	var err error

	attrTypes["_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_hidden"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_hidden_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_no_delete"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_no_edit"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["blocked"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["dev_id_override"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["fixed_ap_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["fixed_ap_mac"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["fixed_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["hostname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_seen"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["local_dns_record"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["local_dns_record_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["mac"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["network_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["note"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["site_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["use_fixedip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["usergroup_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["virtual_network_override_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["virtual_network_override_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 24)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_id"] = val

		val, err = v.AttrHidden.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden"] = val

		val, err = v.AttrHiddenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden_id"] = val

		val, err = v.AttrNoDelete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_delete"] = val

		val, err = v.AttrNoEdit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_edit"] = val

		val, err = v.Blocked.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["blocked"] = val

		val, err = v.DevIdOverride.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dev_id_override"] = val

		val, err = v.FixedApEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fixed_ap_enabled"] = val

		val, err = v.FixedApMac.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fixed_ap_mac"] = val

		val, err = v.FixedIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fixed_ip"] = val

		val, err = v.Hostname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hostname"] = val

		val, err = v.Ip.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip"] = val

		val, err = v.LastSeen.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_seen"] = val

		val, err = v.LocalDnsRecord.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["local_dns_record"] = val

		val, err = v.LocalDnsRecordEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["local_dns_record_enabled"] = val

		val, err = v.Mac.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["mac"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.NetworkId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["network_id"] = val

		val, err = v.Note.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["note"] = val

		val, err = v.SiteId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site_id"] = val

		val, err = v.UseFixedip.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["use_fixedip"] = val

		val, err = v.UsergroupId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["usergroup_id"] = val

		val, err = v.VirtualNetworkOverrideEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["virtual_network_override_enabled"] = val

		val, err = v.VirtualNetworkOverrideId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["virtual_network_override_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"_id":                              basetypes.StringType{},
		"attr_hidden":                      basetypes.BoolType{},
		"attr_hidden_id":                   basetypes.StringType{},
		"attr_no_delete":                   basetypes.BoolType{},
		"attr_no_edit":                     basetypes.BoolType{},
		"blocked":                          basetypes.BoolType{},
		"dev_id_override":                  basetypes.Int64Type{},
		"fixed_ap_enabled":                 basetypes.BoolType{},
		"fixed_ap_mac":                     basetypes.StringType{},
		"fixed_ip":                         basetypes.StringType{},
		"hostname":                         basetypes.StringType{},
		"ip":                               basetypes.StringType{},
		"last_seen":                        basetypes.Int64Type{},
		"local_dns_record":                 basetypes.StringType{},
		"local_dns_record_enabled":         basetypes.BoolType{},
		"mac":                              basetypes.StringType{},
		"name":                             basetypes.StringType{},
		"network_id":                       basetypes.StringType{},
		"note":                             basetypes.StringType{},
		"site_id":                          basetypes.StringType{},
		"use_fixedip":                      basetypes.BoolType{},
		"usergroup_id":                     basetypes.StringType{},
		"virtual_network_override_enabled": basetypes.BoolType{},
		"virtual_network_override_id":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_id":                              v.Id,
			"attr_hidden":                      v.AttrHidden,
			"attr_hidden_id":                   v.AttrHiddenId,
			"attr_no_delete":                   v.AttrNoDelete,
			"attr_no_edit":                     v.AttrNoEdit,
			"blocked":                          v.Blocked,
			"dev_id_override":                  v.DevIdOverride,
			"fixed_ap_enabled":                 v.FixedApEnabled,
			"fixed_ap_mac":                     v.FixedApMac,
			"fixed_ip":                         v.FixedIp,
			"hostname":                         v.Hostname,
			"ip":                               v.Ip,
			"last_seen":                        v.LastSeen,
			"local_dns_record":                 v.LocalDnsRecord,
			"local_dns_record_enabled":         v.LocalDnsRecordEnabled,
			"mac":                              v.Mac,
			"name":                             v.Name,
			"network_id":                       v.NetworkId,
			"note":                             v.Note,
			"site_id":                          v.SiteId,
			"use_fixedip":                      v.UseFixedip,
			"usergroup_id":                     v.UsergroupId,
			"virtual_network_override_enabled": v.VirtualNetworkOverrideEnabled,
			"virtual_network_override_id":      v.VirtualNetworkOverrideId,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.AttrHidden.Equal(other.AttrHidden) {
		return false
	}

	if !v.AttrHiddenId.Equal(other.AttrHiddenId) {
		return false
	}

	if !v.AttrNoDelete.Equal(other.AttrNoDelete) {
		return false
	}

	if !v.AttrNoEdit.Equal(other.AttrNoEdit) {
		return false
	}

	if !v.Blocked.Equal(other.Blocked) {
		return false
	}

	if !v.DevIdOverride.Equal(other.DevIdOverride) {
		return false
	}

	if !v.FixedApEnabled.Equal(other.FixedApEnabled) {
		return false
	}

	if !v.FixedApMac.Equal(other.FixedApMac) {
		return false
	}

	if !v.FixedIp.Equal(other.FixedIp) {
		return false
	}

	if !v.Hostname.Equal(other.Hostname) {
		return false
	}

	if !v.Ip.Equal(other.Ip) {
		return false
	}

	if !v.LastSeen.Equal(other.LastSeen) {
		return false
	}

	if !v.LocalDnsRecord.Equal(other.LocalDnsRecord) {
		return false
	}

	if !v.LocalDnsRecordEnabled.Equal(other.LocalDnsRecordEnabled) {
		return false
	}

	if !v.Mac.Equal(other.Mac) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.NetworkId.Equal(other.NetworkId) {
		return false
	}

	if !v.Note.Equal(other.Note) {
		return false
	}

	if !v.SiteId.Equal(other.SiteId) {
		return false
	}

	if !v.UseFixedip.Equal(other.UseFixedip) {
		return false
	}

	if !v.UsergroupId.Equal(other.UsergroupId) {
		return false
	}

	if !v.VirtualNetworkOverrideEnabled.Equal(other.VirtualNetworkOverrideEnabled) {
		return false
	}

	if !v.VirtualNetworkOverrideId.Equal(other.VirtualNetworkOverrideId) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_id":                              basetypes.StringType{},
		"attr_hidden":                      basetypes.BoolType{},
		"attr_hidden_id":                   basetypes.StringType{},
		"attr_no_delete":                   basetypes.BoolType{},
		"attr_no_edit":                     basetypes.BoolType{},
		"blocked":                          basetypes.BoolType{},
		"dev_id_override":                  basetypes.Int64Type{},
		"fixed_ap_enabled":                 basetypes.BoolType{},
		"fixed_ap_mac":                     basetypes.StringType{},
		"fixed_ip":                         basetypes.StringType{},
		"hostname":                         basetypes.StringType{},
		"ip":                               basetypes.StringType{},
		"last_seen":                        basetypes.Int64Type{},
		"local_dns_record":                 basetypes.StringType{},
		"local_dns_record_enabled":         basetypes.BoolType{},
		"mac":                              basetypes.StringType{},
		"name":                             basetypes.StringType{},
		"network_id":                       basetypes.StringType{},
		"note":                             basetypes.StringType{},
		"site_id":                          basetypes.StringType{},
		"use_fixedip":                      basetypes.BoolType{},
		"usergroup_id":                     basetypes.StringType{},
		"virtual_network_override_enabled": basetypes.BoolType{},
		"virtual_network_override_id":      basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = MetaType{}

type MetaType struct {
	basetypes.ObjectType
}

func (t MetaType) Equal(o attr.Type) bool {
	other, ok := o.(MetaType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetaType) String() string {
	return "MetaType"
}

func (t MetaType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return nil, diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueNull() MetaValue {
	return MetaValue{
		state: attr.ValueStateNull,
	}
}

func NewMetaValueUnknown() MetaValue {
	return MetaValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetaValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetaValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetaValue Attribute Value",
				"While creating a MetaValue value, a missing attribute value was detected. "+
					"A MetaValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetaValue Attribute Type",
				"While creating a MetaValue value, an invalid attribute value was detected. "+
					"A MetaValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetaValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetaValue Attribute Value",
				"While creating a MetaValue value, an extra attribute value was detected. "+
					"A MetaValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetaValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetaValue {
	object, diags := NewMetaValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetaValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetaType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetaValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetaValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetaValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetaValueMust(MetaValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetaType) ValueType(ctx context.Context) attr.Value {
	return MetaValue{}
}

var _ basetypes.ObjectValuable = MetaValue{}

type MetaValue struct {
	Msg   basetypes.StringValue `tfsdk:"msg"`
	Rc    basetypes.StringValue `tfsdk:"rc"`
	state attr.ValueState
}

func (v MetaValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rc"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.Rc.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rc"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetaValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetaValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetaValue) String() string {
	return "MetaValue"
}

func (v MetaValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"msg": v.Msg,
			"rc":  v.Rc,
		})

	return objVal, diags
}

func (v MetaValue) Equal(o attr.Value) bool {
	other, ok := o.(MetaValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.Rc.Equal(other.Rc) {
		return false
	}

	return true
}

func (v MetaValue) Type(ctx context.Context) attr.Type {
	return MetaType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetaValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}
}
