// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_firewall_rule

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func FirewallRuleDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_id": schema.StringAttribute{
							Computed: true,
						},
						"action": schema.StringAttribute{
							Computed: true,
						},
						"attr_hidden": schema.BoolAttribute{
							Computed: true,
						},
						"attr_hidden_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_no_delete": schema.BoolAttribute{
							Computed: true,
						},
						"attr_no_edit": schema.BoolAttribute{
							Computed: true,
						},
						"dst_address": schema.StringAttribute{
							Computed: true,
						},
						"dst_address_ipv6": schema.StringAttribute{
							Computed: true,
						},
						"dst_firewallgroup_ids": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"dst_networkconf_id": schema.StringAttribute{
							Computed: true,
						},
						"dst_networkconf_type": schema.StringAttribute{
							Computed: true,
						},
						"dst_port": schema.StringAttribute{
							Computed: true,
						},
						"enabled": schema.BoolAttribute{
							Computed: true,
						},
						"icmp_typename": schema.StringAttribute{
							Computed: true,
						},
						"icmpv6_typename": schema.StringAttribute{
							Computed: true,
						},
						"ipsec": schema.StringAttribute{
							Computed: true,
						},
						"logging": schema.BoolAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"protocol": schema.StringAttribute{
							Computed: true,
						},
						"protocol_match_excepted": schema.BoolAttribute{
							Computed: true,
						},
						"protocol_v6": schema.StringAttribute{
							Computed: true,
						},
						"rule_index": schema.Int64Attribute{
							Computed: true,
						},
						"ruleset": schema.StringAttribute{
							Computed: true,
						},
						"setting_preference": schema.StringAttribute{
							Computed: true,
						},
						"site_id": schema.StringAttribute{
							Computed: true,
						},
						"src_address": schema.StringAttribute{
							Computed: true,
						},
						"src_address_ipv6": schema.StringAttribute{
							Computed: true,
						},
						"src_firewallgroup_ids": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"src_mac_address": schema.StringAttribute{
							Computed: true,
						},
						"src_networkconf_id": schema.StringAttribute{
							Computed: true,
						},
						"src_networkconf_type": schema.StringAttribute{
							Computed: true,
						},
						"src_port": schema.StringAttribute{
							Computed: true,
						},
						"state_established": schema.BoolAttribute{
							Computed: true,
						},
						"state_invalid": schema.BoolAttribute{
							Computed: true,
						},
						"state_new": schema.BoolAttribute{
							Computed: true,
						},
						"state_related": schema.BoolAttribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"meta": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"msg": schema.StringAttribute{
						Computed: true,
					},
					"rc": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetaType{
					ObjectType: types.ObjectType{
						AttrTypes: MetaValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type FirewallRuleModel struct {
	Data types.List   `tfsdk:"data"`
	Id   types.String `tfsdk:"id"`
	Meta MetaValue    `tfsdk:"meta"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	actionAttribute, ok := attributes["action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action is missing from object`)

		return nil, diags
	}

	actionVal, ok := actionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action expected to be basetypes.StringValue, was: %T`, actionAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return nil, diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return nil, diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return nil, diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return nil, diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	dstAddressAttribute, ok := attributes["dst_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_address is missing from object`)

		return nil, diags
	}

	dstAddressVal, ok := dstAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_address expected to be basetypes.StringValue, was: %T`, dstAddressAttribute))
	}

	dstAddressIpv6Attribute, ok := attributes["dst_address_ipv6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_address_ipv6 is missing from object`)

		return nil, diags
	}

	dstAddressIpv6Val, ok := dstAddressIpv6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_address_ipv6 expected to be basetypes.StringValue, was: %T`, dstAddressIpv6Attribute))
	}

	dstFirewallgroupIdsAttribute, ok := attributes["dst_firewallgroup_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_firewallgroup_ids is missing from object`)

		return nil, diags
	}

	dstFirewallgroupIdsVal, ok := dstFirewallgroupIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_firewallgroup_ids expected to be basetypes.ListValue, was: %T`, dstFirewallgroupIdsAttribute))
	}

	dstNetworkconfIdAttribute, ok := attributes["dst_networkconf_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_networkconf_id is missing from object`)

		return nil, diags
	}

	dstNetworkconfIdVal, ok := dstNetworkconfIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_networkconf_id expected to be basetypes.StringValue, was: %T`, dstNetworkconfIdAttribute))
	}

	dstNetworkconfTypeAttribute, ok := attributes["dst_networkconf_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_networkconf_type is missing from object`)

		return nil, diags
	}

	dstNetworkconfTypeVal, ok := dstNetworkconfTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_networkconf_type expected to be basetypes.StringValue, was: %T`, dstNetworkconfTypeAttribute))
	}

	dstPortAttribute, ok := attributes["dst_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_port is missing from object`)

		return nil, diags
	}

	dstPortVal, ok := dstPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_port expected to be basetypes.StringValue, was: %T`, dstPortAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return nil, diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	icmpTypenameAttribute, ok := attributes["icmp_typename"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icmp_typename is missing from object`)

		return nil, diags
	}

	icmpTypenameVal, ok := icmpTypenameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icmp_typename expected to be basetypes.StringValue, was: %T`, icmpTypenameAttribute))
	}

	icmpv6TypenameAttribute, ok := attributes["icmpv6_typename"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icmpv6_typename is missing from object`)

		return nil, diags
	}

	icmpv6TypenameVal, ok := icmpv6TypenameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icmpv6_typename expected to be basetypes.StringValue, was: %T`, icmpv6TypenameAttribute))
	}

	ipsecAttribute, ok := attributes["ipsec"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ipsec is missing from object`)

		return nil, diags
	}

	ipsecVal, ok := ipsecAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ipsec expected to be basetypes.StringValue, was: %T`, ipsecAttribute))
	}

	loggingAttribute, ok := attributes["logging"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`logging is missing from object`)

		return nil, diags
	}

	loggingVal, ok := loggingAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`logging expected to be basetypes.BoolValue, was: %T`, loggingAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	protocolAttribute, ok := attributes["protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol is missing from object`)

		return nil, diags
	}

	protocolVal, ok := protocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol expected to be basetypes.StringValue, was: %T`, protocolAttribute))
	}

	protocolMatchExceptedAttribute, ok := attributes["protocol_match_excepted"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol_match_excepted is missing from object`)

		return nil, diags
	}

	protocolMatchExceptedVal, ok := protocolMatchExceptedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol_match_excepted expected to be basetypes.BoolValue, was: %T`, protocolMatchExceptedAttribute))
	}

	protocolV6Attribute, ok := attributes["protocol_v6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol_v6 is missing from object`)

		return nil, diags
	}

	protocolV6Val, ok := protocolV6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol_v6 expected to be basetypes.StringValue, was: %T`, protocolV6Attribute))
	}

	ruleIndexAttribute, ok := attributes["rule_index"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rule_index is missing from object`)

		return nil, diags
	}

	ruleIndexVal, ok := ruleIndexAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rule_index expected to be basetypes.Int64Value, was: %T`, ruleIndexAttribute))
	}

	rulesetAttribute, ok := attributes["ruleset"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ruleset is missing from object`)

		return nil, diags
	}

	rulesetVal, ok := rulesetAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ruleset expected to be basetypes.StringValue, was: %T`, rulesetAttribute))
	}

	settingPreferenceAttribute, ok := attributes["setting_preference"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`setting_preference is missing from object`)

		return nil, diags
	}

	settingPreferenceVal, ok := settingPreferenceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`setting_preference expected to be basetypes.StringValue, was: %T`, settingPreferenceAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return nil, diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	srcAddressAttribute, ok := attributes["src_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_address is missing from object`)

		return nil, diags
	}

	srcAddressVal, ok := srcAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_address expected to be basetypes.StringValue, was: %T`, srcAddressAttribute))
	}

	srcAddressIpv6Attribute, ok := attributes["src_address_ipv6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_address_ipv6 is missing from object`)

		return nil, diags
	}

	srcAddressIpv6Val, ok := srcAddressIpv6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_address_ipv6 expected to be basetypes.StringValue, was: %T`, srcAddressIpv6Attribute))
	}

	srcFirewallgroupIdsAttribute, ok := attributes["src_firewallgroup_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_firewallgroup_ids is missing from object`)

		return nil, diags
	}

	srcFirewallgroupIdsVal, ok := srcFirewallgroupIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_firewallgroup_ids expected to be basetypes.ListValue, was: %T`, srcFirewallgroupIdsAttribute))
	}

	srcMacAddressAttribute, ok := attributes["src_mac_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_mac_address is missing from object`)

		return nil, diags
	}

	srcMacAddressVal, ok := srcMacAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_mac_address expected to be basetypes.StringValue, was: %T`, srcMacAddressAttribute))
	}

	srcNetworkconfIdAttribute, ok := attributes["src_networkconf_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_networkconf_id is missing from object`)

		return nil, diags
	}

	srcNetworkconfIdVal, ok := srcNetworkconfIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_networkconf_id expected to be basetypes.StringValue, was: %T`, srcNetworkconfIdAttribute))
	}

	srcNetworkconfTypeAttribute, ok := attributes["src_networkconf_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_networkconf_type is missing from object`)

		return nil, diags
	}

	srcNetworkconfTypeVal, ok := srcNetworkconfTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_networkconf_type expected to be basetypes.StringValue, was: %T`, srcNetworkconfTypeAttribute))
	}

	srcPortAttribute, ok := attributes["src_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_port is missing from object`)

		return nil, diags
	}

	srcPortVal, ok := srcPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_port expected to be basetypes.StringValue, was: %T`, srcPortAttribute))
	}

	stateEstablishedAttribute, ok := attributes["state_established"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_established is missing from object`)

		return nil, diags
	}

	stateEstablishedVal, ok := stateEstablishedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_established expected to be basetypes.BoolValue, was: %T`, stateEstablishedAttribute))
	}

	stateInvalidAttribute, ok := attributes["state_invalid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_invalid is missing from object`)

		return nil, diags
	}

	stateInvalidVal, ok := stateInvalidAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_invalid expected to be basetypes.BoolValue, was: %T`, stateInvalidAttribute))
	}

	stateNewAttribute, ok := attributes["state_new"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_new is missing from object`)

		return nil, diags
	}

	stateNewVal, ok := stateNewAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_new expected to be basetypes.BoolValue, was: %T`, stateNewAttribute))
	}

	stateRelatedAttribute, ok := attributes["state_related"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_related is missing from object`)

		return nil, diags
	}

	stateRelatedVal, ok := stateRelatedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_related expected to be basetypes.BoolValue, was: %T`, stateRelatedAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Id:                    idVal,
		Action:                actionVal,
		AttrHidden:            attrHiddenVal,
		AttrHiddenId:          attrHiddenIdVal,
		AttrNoDelete:          attrNoDeleteVal,
		AttrNoEdit:            attrNoEditVal,
		DstAddress:            dstAddressVal,
		DstAddressIpv6:        dstAddressIpv6Val,
		DstFirewallgroupIds:   dstFirewallgroupIdsVal,
		DstNetworkconfId:      dstNetworkconfIdVal,
		DstNetworkconfType:    dstNetworkconfTypeVal,
		DstPort:               dstPortVal,
		Enabled:               enabledVal,
		IcmpTypename:          icmpTypenameVal,
		Icmpv6Typename:        icmpv6TypenameVal,
		Ipsec:                 ipsecVal,
		Logging:               loggingVal,
		Name:                  nameVal,
		Protocol:              protocolVal,
		ProtocolMatchExcepted: protocolMatchExceptedVal,
		ProtocolV6:            protocolV6Val,
		RuleIndex:             ruleIndexVal,
		Ruleset:               rulesetVal,
		SettingPreference:     settingPreferenceVal,
		SiteId:                siteIdVal,
		SrcAddress:            srcAddressVal,
		SrcAddressIpv6:        srcAddressIpv6Val,
		SrcFirewallgroupIds:   srcFirewallgroupIdsVal,
		SrcMacAddress:         srcMacAddressVal,
		SrcNetworkconfId:      srcNetworkconfIdVal,
		SrcNetworkconfType:    srcNetworkconfTypeVal,
		SrcPort:               srcPortVal,
		StateEstablished:      stateEstablishedVal,
		StateInvalid:          stateInvalidVal,
		StateNew:              stateNewVal,
		StateRelated:          stateRelatedVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	actionAttribute, ok := attributes["action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action is missing from object`)

		return NewDataValueUnknown(), diags
	}

	actionVal, ok := actionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action expected to be basetypes.StringValue, was: %T`, actionAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	dstAddressAttribute, ok := attributes["dst_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_address is missing from object`)

		return NewDataValueUnknown(), diags
	}

	dstAddressVal, ok := dstAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_address expected to be basetypes.StringValue, was: %T`, dstAddressAttribute))
	}

	dstAddressIpv6Attribute, ok := attributes["dst_address_ipv6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_address_ipv6 is missing from object`)

		return NewDataValueUnknown(), diags
	}

	dstAddressIpv6Val, ok := dstAddressIpv6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_address_ipv6 expected to be basetypes.StringValue, was: %T`, dstAddressIpv6Attribute))
	}

	dstFirewallgroupIdsAttribute, ok := attributes["dst_firewallgroup_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_firewallgroup_ids is missing from object`)

		return NewDataValueUnknown(), diags
	}

	dstFirewallgroupIdsVal, ok := dstFirewallgroupIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_firewallgroup_ids expected to be basetypes.ListValue, was: %T`, dstFirewallgroupIdsAttribute))
	}

	dstNetworkconfIdAttribute, ok := attributes["dst_networkconf_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_networkconf_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	dstNetworkconfIdVal, ok := dstNetworkconfIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_networkconf_id expected to be basetypes.StringValue, was: %T`, dstNetworkconfIdAttribute))
	}

	dstNetworkconfTypeAttribute, ok := attributes["dst_networkconf_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_networkconf_type is missing from object`)

		return NewDataValueUnknown(), diags
	}

	dstNetworkconfTypeVal, ok := dstNetworkconfTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_networkconf_type expected to be basetypes.StringValue, was: %T`, dstNetworkconfTypeAttribute))
	}

	dstPortAttribute, ok := attributes["dst_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dst_port is missing from object`)

		return NewDataValueUnknown(), diags
	}

	dstPortVal, ok := dstPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dst_port expected to be basetypes.StringValue, was: %T`, dstPortAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	icmpTypenameAttribute, ok := attributes["icmp_typename"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icmp_typename is missing from object`)

		return NewDataValueUnknown(), diags
	}

	icmpTypenameVal, ok := icmpTypenameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icmp_typename expected to be basetypes.StringValue, was: %T`, icmpTypenameAttribute))
	}

	icmpv6TypenameAttribute, ok := attributes["icmpv6_typename"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icmpv6_typename is missing from object`)

		return NewDataValueUnknown(), diags
	}

	icmpv6TypenameVal, ok := icmpv6TypenameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icmpv6_typename expected to be basetypes.StringValue, was: %T`, icmpv6TypenameAttribute))
	}

	ipsecAttribute, ok := attributes["ipsec"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ipsec is missing from object`)

		return NewDataValueUnknown(), diags
	}

	ipsecVal, ok := ipsecAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ipsec expected to be basetypes.StringValue, was: %T`, ipsecAttribute))
	}

	loggingAttribute, ok := attributes["logging"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`logging is missing from object`)

		return NewDataValueUnknown(), diags
	}

	loggingVal, ok := loggingAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`logging expected to be basetypes.BoolValue, was: %T`, loggingAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	protocolAttribute, ok := attributes["protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol is missing from object`)

		return NewDataValueUnknown(), diags
	}

	protocolVal, ok := protocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol expected to be basetypes.StringValue, was: %T`, protocolAttribute))
	}

	protocolMatchExceptedAttribute, ok := attributes["protocol_match_excepted"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol_match_excepted is missing from object`)

		return NewDataValueUnknown(), diags
	}

	protocolMatchExceptedVal, ok := protocolMatchExceptedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol_match_excepted expected to be basetypes.BoolValue, was: %T`, protocolMatchExceptedAttribute))
	}

	protocolV6Attribute, ok := attributes["protocol_v6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol_v6 is missing from object`)

		return NewDataValueUnknown(), diags
	}

	protocolV6Val, ok := protocolV6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol_v6 expected to be basetypes.StringValue, was: %T`, protocolV6Attribute))
	}

	ruleIndexAttribute, ok := attributes["rule_index"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rule_index is missing from object`)

		return NewDataValueUnknown(), diags
	}

	ruleIndexVal, ok := ruleIndexAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rule_index expected to be basetypes.Int64Value, was: %T`, ruleIndexAttribute))
	}

	rulesetAttribute, ok := attributes["ruleset"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ruleset is missing from object`)

		return NewDataValueUnknown(), diags
	}

	rulesetVal, ok := rulesetAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ruleset expected to be basetypes.StringValue, was: %T`, rulesetAttribute))
	}

	settingPreferenceAttribute, ok := attributes["setting_preference"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`setting_preference is missing from object`)

		return NewDataValueUnknown(), diags
	}

	settingPreferenceVal, ok := settingPreferenceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`setting_preference expected to be basetypes.StringValue, was: %T`, settingPreferenceAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	srcAddressAttribute, ok := attributes["src_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_address is missing from object`)

		return NewDataValueUnknown(), diags
	}

	srcAddressVal, ok := srcAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_address expected to be basetypes.StringValue, was: %T`, srcAddressAttribute))
	}

	srcAddressIpv6Attribute, ok := attributes["src_address_ipv6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_address_ipv6 is missing from object`)

		return NewDataValueUnknown(), diags
	}

	srcAddressIpv6Val, ok := srcAddressIpv6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_address_ipv6 expected to be basetypes.StringValue, was: %T`, srcAddressIpv6Attribute))
	}

	srcFirewallgroupIdsAttribute, ok := attributes["src_firewallgroup_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_firewallgroup_ids is missing from object`)

		return NewDataValueUnknown(), diags
	}

	srcFirewallgroupIdsVal, ok := srcFirewallgroupIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_firewallgroup_ids expected to be basetypes.ListValue, was: %T`, srcFirewallgroupIdsAttribute))
	}

	srcMacAddressAttribute, ok := attributes["src_mac_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_mac_address is missing from object`)

		return NewDataValueUnknown(), diags
	}

	srcMacAddressVal, ok := srcMacAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_mac_address expected to be basetypes.StringValue, was: %T`, srcMacAddressAttribute))
	}

	srcNetworkconfIdAttribute, ok := attributes["src_networkconf_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_networkconf_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	srcNetworkconfIdVal, ok := srcNetworkconfIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_networkconf_id expected to be basetypes.StringValue, was: %T`, srcNetworkconfIdAttribute))
	}

	srcNetworkconfTypeAttribute, ok := attributes["src_networkconf_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_networkconf_type is missing from object`)

		return NewDataValueUnknown(), diags
	}

	srcNetworkconfTypeVal, ok := srcNetworkconfTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_networkconf_type expected to be basetypes.StringValue, was: %T`, srcNetworkconfTypeAttribute))
	}

	srcPortAttribute, ok := attributes["src_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`src_port is missing from object`)

		return NewDataValueUnknown(), diags
	}

	srcPortVal, ok := srcPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`src_port expected to be basetypes.StringValue, was: %T`, srcPortAttribute))
	}

	stateEstablishedAttribute, ok := attributes["state_established"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_established is missing from object`)

		return NewDataValueUnknown(), diags
	}

	stateEstablishedVal, ok := stateEstablishedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_established expected to be basetypes.BoolValue, was: %T`, stateEstablishedAttribute))
	}

	stateInvalidAttribute, ok := attributes["state_invalid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_invalid is missing from object`)

		return NewDataValueUnknown(), diags
	}

	stateInvalidVal, ok := stateInvalidAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_invalid expected to be basetypes.BoolValue, was: %T`, stateInvalidAttribute))
	}

	stateNewAttribute, ok := attributes["state_new"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_new is missing from object`)

		return NewDataValueUnknown(), diags
	}

	stateNewVal, ok := stateNewAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_new expected to be basetypes.BoolValue, was: %T`, stateNewAttribute))
	}

	stateRelatedAttribute, ok := attributes["state_related"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_related is missing from object`)

		return NewDataValueUnknown(), diags
	}

	stateRelatedVal, ok := stateRelatedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_related expected to be basetypes.BoolValue, was: %T`, stateRelatedAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Id:                    idVal,
		Action:                actionVal,
		AttrHidden:            attrHiddenVal,
		AttrHiddenId:          attrHiddenIdVal,
		AttrNoDelete:          attrNoDeleteVal,
		AttrNoEdit:            attrNoEditVal,
		DstAddress:            dstAddressVal,
		DstAddressIpv6:        dstAddressIpv6Val,
		DstFirewallgroupIds:   dstFirewallgroupIdsVal,
		DstNetworkconfId:      dstNetworkconfIdVal,
		DstNetworkconfType:    dstNetworkconfTypeVal,
		DstPort:               dstPortVal,
		Enabled:               enabledVal,
		IcmpTypename:          icmpTypenameVal,
		Icmpv6Typename:        icmpv6TypenameVal,
		Ipsec:                 ipsecVal,
		Logging:               loggingVal,
		Name:                  nameVal,
		Protocol:              protocolVal,
		ProtocolMatchExcepted: protocolMatchExceptedVal,
		ProtocolV6:            protocolV6Val,
		RuleIndex:             ruleIndexVal,
		Ruleset:               rulesetVal,
		SettingPreference:     settingPreferenceVal,
		SiteId:                siteIdVal,
		SrcAddress:            srcAddressVal,
		SrcAddressIpv6:        srcAddressIpv6Val,
		SrcFirewallgroupIds:   srcFirewallgroupIdsVal,
		SrcMacAddress:         srcMacAddressVal,
		SrcNetworkconfId:      srcNetworkconfIdVal,
		SrcNetworkconfType:    srcNetworkconfTypeVal,
		SrcPort:               srcPortVal,
		StateEstablished:      stateEstablishedVal,
		StateInvalid:          stateInvalidVal,
		StateNew:              stateNewVal,
		StateRelated:          stateRelatedVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Id                    basetypes.StringValue `tfsdk:"_id"`
	Action                basetypes.StringValue `tfsdk:"action"`
	AttrHidden            basetypes.BoolValue   `tfsdk:"attr_hidden"`
	AttrHiddenId          basetypes.StringValue `tfsdk:"attr_hidden_id"`
	AttrNoDelete          basetypes.BoolValue   `tfsdk:"attr_no_delete"`
	AttrNoEdit            basetypes.BoolValue   `tfsdk:"attr_no_edit"`
	DstAddress            basetypes.StringValue `tfsdk:"dst_address"`
	DstAddressIpv6        basetypes.StringValue `tfsdk:"dst_address_ipv6"`
	DstFirewallgroupIds   basetypes.ListValue   `tfsdk:"dst_firewallgroup_ids"`
	DstNetworkconfId      basetypes.StringValue `tfsdk:"dst_networkconf_id"`
	DstNetworkconfType    basetypes.StringValue `tfsdk:"dst_networkconf_type"`
	DstPort               basetypes.StringValue `tfsdk:"dst_port"`
	Enabled               basetypes.BoolValue   `tfsdk:"enabled"`
	IcmpTypename          basetypes.StringValue `tfsdk:"icmp_typename"`
	Icmpv6Typename        basetypes.StringValue `tfsdk:"icmpv6_typename"`
	Ipsec                 basetypes.StringValue `tfsdk:"ipsec"`
	Logging               basetypes.BoolValue   `tfsdk:"logging"`
	Name                  basetypes.StringValue `tfsdk:"name"`
	Protocol              basetypes.StringValue `tfsdk:"protocol"`
	ProtocolMatchExcepted basetypes.BoolValue   `tfsdk:"protocol_match_excepted"`
	ProtocolV6            basetypes.StringValue `tfsdk:"protocol_v6"`
	RuleIndex             basetypes.Int64Value  `tfsdk:"rule_index"`
	Ruleset               basetypes.StringValue `tfsdk:"ruleset"`
	SettingPreference     basetypes.StringValue `tfsdk:"setting_preference"`
	SiteId                basetypes.StringValue `tfsdk:"site_id"`
	SrcAddress            basetypes.StringValue `tfsdk:"src_address"`
	SrcAddressIpv6        basetypes.StringValue `tfsdk:"src_address_ipv6"`
	SrcFirewallgroupIds   basetypes.ListValue   `tfsdk:"src_firewallgroup_ids"`
	SrcMacAddress         basetypes.StringValue `tfsdk:"src_mac_address"`
	SrcNetworkconfId      basetypes.StringValue `tfsdk:"src_networkconf_id"`
	SrcNetworkconfType    basetypes.StringValue `tfsdk:"src_networkconf_type"`
	SrcPort               basetypes.StringValue `tfsdk:"src_port"`
	StateEstablished      basetypes.BoolValue   `tfsdk:"state_established"`
	StateInvalid          basetypes.BoolValue   `tfsdk:"state_invalid"`
	StateNew              basetypes.BoolValue   `tfsdk:"state_new"`
	StateRelated          basetypes.BoolValue   `tfsdk:"state_related"`
	state                 attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 36)

	var val tftypes.Value
	var err error

	attrTypes["_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["action"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_hidden"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_hidden_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_no_delete"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_no_edit"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["dst_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dst_address_ipv6"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dst_firewallgroup_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["dst_networkconf_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dst_networkconf_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dst_port"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["icmp_typename"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["icmpv6_typename"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ipsec"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["logging"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["protocol"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["protocol_match_excepted"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["protocol_v6"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rule_index"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["ruleset"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["setting_preference"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["site_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["src_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["src_address_ipv6"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["src_firewallgroup_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["src_mac_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["src_networkconf_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["src_networkconf_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["src_port"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["state_established"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["state_invalid"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["state_new"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["state_related"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 36)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_id"] = val

		val, err = v.Action.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["action"] = val

		val, err = v.AttrHidden.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden"] = val

		val, err = v.AttrHiddenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden_id"] = val

		val, err = v.AttrNoDelete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_delete"] = val

		val, err = v.AttrNoEdit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_edit"] = val

		val, err = v.DstAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dst_address"] = val

		val, err = v.DstAddressIpv6.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dst_address_ipv6"] = val

		val, err = v.DstFirewallgroupIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dst_firewallgroup_ids"] = val

		val, err = v.DstNetworkconfId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dst_networkconf_id"] = val

		val, err = v.DstNetworkconfType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dst_networkconf_type"] = val

		val, err = v.DstPort.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dst_port"] = val

		val, err = v.Enabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["enabled"] = val

		val, err = v.IcmpTypename.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["icmp_typename"] = val

		val, err = v.Icmpv6Typename.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["icmpv6_typename"] = val

		val, err = v.Ipsec.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ipsec"] = val

		val, err = v.Logging.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["logging"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Protocol.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["protocol"] = val

		val, err = v.ProtocolMatchExcepted.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["protocol_match_excepted"] = val

		val, err = v.ProtocolV6.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["protocol_v6"] = val

		val, err = v.RuleIndex.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rule_index"] = val

		val, err = v.Ruleset.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ruleset"] = val

		val, err = v.SettingPreference.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["setting_preference"] = val

		val, err = v.SiteId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site_id"] = val

		val, err = v.SrcAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["src_address"] = val

		val, err = v.SrcAddressIpv6.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["src_address_ipv6"] = val

		val, err = v.SrcFirewallgroupIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["src_firewallgroup_ids"] = val

		val, err = v.SrcMacAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["src_mac_address"] = val

		val, err = v.SrcNetworkconfId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["src_networkconf_id"] = val

		val, err = v.SrcNetworkconfType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["src_networkconf_type"] = val

		val, err = v.SrcPort.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["src_port"] = val

		val, err = v.StateEstablished.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state_established"] = val

		val, err = v.StateInvalid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state_invalid"] = val

		val, err = v.StateNew.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state_new"] = val

		val, err = v.StateRelated.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state_related"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var dstFirewallgroupIdsVal basetypes.ListValue
	switch {
	case v.DstFirewallgroupIds.IsUnknown():
		dstFirewallgroupIdsVal = types.ListUnknown(types.StringType)
	case v.DstFirewallgroupIds.IsNull():
		dstFirewallgroupIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		dstFirewallgroupIdsVal, d = types.ListValue(types.StringType, v.DstFirewallgroupIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"_id":              basetypes.StringType{},
			"action":           basetypes.StringType{},
			"attr_hidden":      basetypes.BoolType{},
			"attr_hidden_id":   basetypes.StringType{},
			"attr_no_delete":   basetypes.BoolType{},
			"attr_no_edit":     basetypes.BoolType{},
			"dst_address":      basetypes.StringType{},
			"dst_address_ipv6": basetypes.StringType{},
			"dst_firewallgroup_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"dst_networkconf_id":      basetypes.StringType{},
			"dst_networkconf_type":    basetypes.StringType{},
			"dst_port":                basetypes.StringType{},
			"enabled":                 basetypes.BoolType{},
			"icmp_typename":           basetypes.StringType{},
			"icmpv6_typename":         basetypes.StringType{},
			"ipsec":                   basetypes.StringType{},
			"logging":                 basetypes.BoolType{},
			"name":                    basetypes.StringType{},
			"protocol":                basetypes.StringType{},
			"protocol_match_excepted": basetypes.BoolType{},
			"protocol_v6":             basetypes.StringType{},
			"rule_index":              basetypes.Int64Type{},
			"ruleset":                 basetypes.StringType{},
			"setting_preference":      basetypes.StringType{},
			"site_id":                 basetypes.StringType{},
			"src_address":             basetypes.StringType{},
			"src_address_ipv6":        basetypes.StringType{},
			"src_firewallgroup_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"src_mac_address":      basetypes.StringType{},
			"src_networkconf_id":   basetypes.StringType{},
			"src_networkconf_type": basetypes.StringType{},
			"src_port":             basetypes.StringType{},
			"state_established":    basetypes.BoolType{},
			"state_invalid":        basetypes.BoolType{},
			"state_new":            basetypes.BoolType{},
			"state_related":        basetypes.BoolType{},
		}), diags
	}

	var srcFirewallgroupIdsVal basetypes.ListValue
	switch {
	case v.SrcFirewallgroupIds.IsUnknown():
		srcFirewallgroupIdsVal = types.ListUnknown(types.StringType)
	case v.SrcFirewallgroupIds.IsNull():
		srcFirewallgroupIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		srcFirewallgroupIdsVal, d = types.ListValue(types.StringType, v.SrcFirewallgroupIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"_id":              basetypes.StringType{},
			"action":           basetypes.StringType{},
			"attr_hidden":      basetypes.BoolType{},
			"attr_hidden_id":   basetypes.StringType{},
			"attr_no_delete":   basetypes.BoolType{},
			"attr_no_edit":     basetypes.BoolType{},
			"dst_address":      basetypes.StringType{},
			"dst_address_ipv6": basetypes.StringType{},
			"dst_firewallgroup_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"dst_networkconf_id":      basetypes.StringType{},
			"dst_networkconf_type":    basetypes.StringType{},
			"dst_port":                basetypes.StringType{},
			"enabled":                 basetypes.BoolType{},
			"icmp_typename":           basetypes.StringType{},
			"icmpv6_typename":         basetypes.StringType{},
			"ipsec":                   basetypes.StringType{},
			"logging":                 basetypes.BoolType{},
			"name":                    basetypes.StringType{},
			"protocol":                basetypes.StringType{},
			"protocol_match_excepted": basetypes.BoolType{},
			"protocol_v6":             basetypes.StringType{},
			"rule_index":              basetypes.Int64Type{},
			"ruleset":                 basetypes.StringType{},
			"setting_preference":      basetypes.StringType{},
			"site_id":                 basetypes.StringType{},
			"src_address":             basetypes.StringType{},
			"src_address_ipv6":        basetypes.StringType{},
			"src_firewallgroup_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"src_mac_address":      basetypes.StringType{},
			"src_networkconf_id":   basetypes.StringType{},
			"src_networkconf_type": basetypes.StringType{},
			"src_port":             basetypes.StringType{},
			"state_established":    basetypes.BoolType{},
			"state_invalid":        basetypes.BoolType{},
			"state_new":            basetypes.BoolType{},
			"state_related":        basetypes.BoolType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"_id":              basetypes.StringType{},
		"action":           basetypes.StringType{},
		"attr_hidden":      basetypes.BoolType{},
		"attr_hidden_id":   basetypes.StringType{},
		"attr_no_delete":   basetypes.BoolType{},
		"attr_no_edit":     basetypes.BoolType{},
		"dst_address":      basetypes.StringType{},
		"dst_address_ipv6": basetypes.StringType{},
		"dst_firewallgroup_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"dst_networkconf_id":      basetypes.StringType{},
		"dst_networkconf_type":    basetypes.StringType{},
		"dst_port":                basetypes.StringType{},
		"enabled":                 basetypes.BoolType{},
		"icmp_typename":           basetypes.StringType{},
		"icmpv6_typename":         basetypes.StringType{},
		"ipsec":                   basetypes.StringType{},
		"logging":                 basetypes.BoolType{},
		"name":                    basetypes.StringType{},
		"protocol":                basetypes.StringType{},
		"protocol_match_excepted": basetypes.BoolType{},
		"protocol_v6":             basetypes.StringType{},
		"rule_index":              basetypes.Int64Type{},
		"ruleset":                 basetypes.StringType{},
		"setting_preference":      basetypes.StringType{},
		"site_id":                 basetypes.StringType{},
		"src_address":             basetypes.StringType{},
		"src_address_ipv6":        basetypes.StringType{},
		"src_firewallgroup_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"src_mac_address":      basetypes.StringType{},
		"src_networkconf_id":   basetypes.StringType{},
		"src_networkconf_type": basetypes.StringType{},
		"src_port":             basetypes.StringType{},
		"state_established":    basetypes.BoolType{},
		"state_invalid":        basetypes.BoolType{},
		"state_new":            basetypes.BoolType{},
		"state_related":        basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_id":                     v.Id,
			"action":                  v.Action,
			"attr_hidden":             v.AttrHidden,
			"attr_hidden_id":          v.AttrHiddenId,
			"attr_no_delete":          v.AttrNoDelete,
			"attr_no_edit":            v.AttrNoEdit,
			"dst_address":             v.DstAddress,
			"dst_address_ipv6":        v.DstAddressIpv6,
			"dst_firewallgroup_ids":   dstFirewallgroupIdsVal,
			"dst_networkconf_id":      v.DstNetworkconfId,
			"dst_networkconf_type":    v.DstNetworkconfType,
			"dst_port":                v.DstPort,
			"enabled":                 v.Enabled,
			"icmp_typename":           v.IcmpTypename,
			"icmpv6_typename":         v.Icmpv6Typename,
			"ipsec":                   v.Ipsec,
			"logging":                 v.Logging,
			"name":                    v.Name,
			"protocol":                v.Protocol,
			"protocol_match_excepted": v.ProtocolMatchExcepted,
			"protocol_v6":             v.ProtocolV6,
			"rule_index":              v.RuleIndex,
			"ruleset":                 v.Ruleset,
			"setting_preference":      v.SettingPreference,
			"site_id":                 v.SiteId,
			"src_address":             v.SrcAddress,
			"src_address_ipv6":        v.SrcAddressIpv6,
			"src_firewallgroup_ids":   srcFirewallgroupIdsVal,
			"src_mac_address":         v.SrcMacAddress,
			"src_networkconf_id":      v.SrcNetworkconfId,
			"src_networkconf_type":    v.SrcNetworkconfType,
			"src_port":                v.SrcPort,
			"state_established":       v.StateEstablished,
			"state_invalid":           v.StateInvalid,
			"state_new":               v.StateNew,
			"state_related":           v.StateRelated,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Action.Equal(other.Action) {
		return false
	}

	if !v.AttrHidden.Equal(other.AttrHidden) {
		return false
	}

	if !v.AttrHiddenId.Equal(other.AttrHiddenId) {
		return false
	}

	if !v.AttrNoDelete.Equal(other.AttrNoDelete) {
		return false
	}

	if !v.AttrNoEdit.Equal(other.AttrNoEdit) {
		return false
	}

	if !v.DstAddress.Equal(other.DstAddress) {
		return false
	}

	if !v.DstAddressIpv6.Equal(other.DstAddressIpv6) {
		return false
	}

	if !v.DstFirewallgroupIds.Equal(other.DstFirewallgroupIds) {
		return false
	}

	if !v.DstNetworkconfId.Equal(other.DstNetworkconfId) {
		return false
	}

	if !v.DstNetworkconfType.Equal(other.DstNetworkconfType) {
		return false
	}

	if !v.DstPort.Equal(other.DstPort) {
		return false
	}

	if !v.Enabled.Equal(other.Enabled) {
		return false
	}

	if !v.IcmpTypename.Equal(other.IcmpTypename) {
		return false
	}

	if !v.Icmpv6Typename.Equal(other.Icmpv6Typename) {
		return false
	}

	if !v.Ipsec.Equal(other.Ipsec) {
		return false
	}

	if !v.Logging.Equal(other.Logging) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Protocol.Equal(other.Protocol) {
		return false
	}

	if !v.ProtocolMatchExcepted.Equal(other.ProtocolMatchExcepted) {
		return false
	}

	if !v.ProtocolV6.Equal(other.ProtocolV6) {
		return false
	}

	if !v.RuleIndex.Equal(other.RuleIndex) {
		return false
	}

	if !v.Ruleset.Equal(other.Ruleset) {
		return false
	}

	if !v.SettingPreference.Equal(other.SettingPreference) {
		return false
	}

	if !v.SiteId.Equal(other.SiteId) {
		return false
	}

	if !v.SrcAddress.Equal(other.SrcAddress) {
		return false
	}

	if !v.SrcAddressIpv6.Equal(other.SrcAddressIpv6) {
		return false
	}

	if !v.SrcFirewallgroupIds.Equal(other.SrcFirewallgroupIds) {
		return false
	}

	if !v.SrcMacAddress.Equal(other.SrcMacAddress) {
		return false
	}

	if !v.SrcNetworkconfId.Equal(other.SrcNetworkconfId) {
		return false
	}

	if !v.SrcNetworkconfType.Equal(other.SrcNetworkconfType) {
		return false
	}

	if !v.SrcPort.Equal(other.SrcPort) {
		return false
	}

	if !v.StateEstablished.Equal(other.StateEstablished) {
		return false
	}

	if !v.StateInvalid.Equal(other.StateInvalid) {
		return false
	}

	if !v.StateNew.Equal(other.StateNew) {
		return false
	}

	if !v.StateRelated.Equal(other.StateRelated) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_id":              basetypes.StringType{},
		"action":           basetypes.StringType{},
		"attr_hidden":      basetypes.BoolType{},
		"attr_hidden_id":   basetypes.StringType{},
		"attr_no_delete":   basetypes.BoolType{},
		"attr_no_edit":     basetypes.BoolType{},
		"dst_address":      basetypes.StringType{},
		"dst_address_ipv6": basetypes.StringType{},
		"dst_firewallgroup_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"dst_networkconf_id":      basetypes.StringType{},
		"dst_networkconf_type":    basetypes.StringType{},
		"dst_port":                basetypes.StringType{},
		"enabled":                 basetypes.BoolType{},
		"icmp_typename":           basetypes.StringType{},
		"icmpv6_typename":         basetypes.StringType{},
		"ipsec":                   basetypes.StringType{},
		"logging":                 basetypes.BoolType{},
		"name":                    basetypes.StringType{},
		"protocol":                basetypes.StringType{},
		"protocol_match_excepted": basetypes.BoolType{},
		"protocol_v6":             basetypes.StringType{},
		"rule_index":              basetypes.Int64Type{},
		"ruleset":                 basetypes.StringType{},
		"setting_preference":      basetypes.StringType{},
		"site_id":                 basetypes.StringType{},
		"src_address":             basetypes.StringType{},
		"src_address_ipv6":        basetypes.StringType{},
		"src_firewallgroup_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"src_mac_address":      basetypes.StringType{},
		"src_networkconf_id":   basetypes.StringType{},
		"src_networkconf_type": basetypes.StringType{},
		"src_port":             basetypes.StringType{},
		"state_established":    basetypes.BoolType{},
		"state_invalid":        basetypes.BoolType{},
		"state_new":            basetypes.BoolType{},
		"state_related":        basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = MetaType{}

type MetaType struct {
	basetypes.ObjectType
}

func (t MetaType) Equal(o attr.Type) bool {
	other, ok := o.(MetaType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetaType) String() string {
	return "MetaType"
}

func (t MetaType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return nil, diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueNull() MetaValue {
	return MetaValue{
		state: attr.ValueStateNull,
	}
}

func NewMetaValueUnknown() MetaValue {
	return MetaValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetaValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetaValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetaValue Attribute Value",
				"While creating a MetaValue value, a missing attribute value was detected. "+
					"A MetaValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetaValue Attribute Type",
				"While creating a MetaValue value, an invalid attribute value was detected. "+
					"A MetaValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetaValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetaValue Attribute Value",
				"While creating a MetaValue value, an extra attribute value was detected. "+
					"A MetaValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetaValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetaValue {
	object, diags := NewMetaValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetaValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetaType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetaValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetaValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetaValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetaValueMust(MetaValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetaType) ValueType(ctx context.Context) attr.Value {
	return MetaValue{}
}

var _ basetypes.ObjectValuable = MetaValue{}

type MetaValue struct {
	Msg   basetypes.StringValue `tfsdk:"msg"`
	Rc    basetypes.StringValue `tfsdk:"rc"`
	state attr.ValueState
}

func (v MetaValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rc"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.Rc.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rc"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetaValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetaValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetaValue) String() string {
	return "MetaValue"
}

func (v MetaValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"msg": v.Msg,
			"rc":  v.Rc,
		})

	return objVal, diags
}

func (v MetaValue) Equal(o attr.Value) bool {
	other, ok := o.(MetaValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.Rc.Equal(other.Rc) {
		return false
	}

	return true
}

func (v MetaValue) Type(ctx context.Context) attr.Type {
	return MetaType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetaValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}
}
