// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_hotspot_package

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func HotspotPackageDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_id": schema.StringAttribute{
							Computed: true,
						},
						"amount": schema.NumberAttribute{
							Computed: true,
						},
						"attr_hidden": schema.BoolAttribute{
							Computed: true,
						},
						"attr_hidden_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_no_delete": schema.BoolAttribute{
							Computed: true,
						},
						"attr_no_edit": schema.BoolAttribute{
							Computed: true,
						},
						"charged_as": schema.StringAttribute{
							Computed: true,
						},
						"currency": schema.StringAttribute{
							Computed: true,
						},
						"custom_payment_fields_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"hours": schema.Int64Attribute{
							Computed: true,
						},
						"index": schema.Int64Attribute{
							Computed: true,
						},
						"limit_down": schema.Int64Attribute{
							Computed: true,
						},
						"limit_overwrite": schema.BoolAttribute{
							Computed: true,
						},
						"limit_quota": schema.Int64Attribute{
							Computed: true,
						},
						"limit_up": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"payment_fields_address_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_address_required": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_city_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_city_required": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_country_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_country_required": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_email_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_email_required": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_first_name_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_first_name_required": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_last_name_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_last_name_required": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_state_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_state_required": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_zip_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"payment_fields_zip_required": schema.BoolAttribute{
							Computed: true,
						},
						"site_id": schema.StringAttribute{
							Computed: true,
						},
						"trial_duration_minutes": schema.Int64Attribute{
							Computed: true,
						},
						"trial_reset": schema.NumberAttribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"meta": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"msg": schema.StringAttribute{
						Computed: true,
					},
					"rc": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetaType{
					ObjectType: types.ObjectType{
						AttrTypes: MetaValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type HotspotPackageModel struct {
	Data types.List   `tfsdk:"data"`
	Id   types.String `tfsdk:"id"`
	Meta MetaValue    `tfsdk:"meta"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return nil, diags
	}

	amountVal, ok := amountAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.NumberValue, was: %T`, amountAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return nil, diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return nil, diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return nil, diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return nil, diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	chargedAsAttribute, ok := attributes["charged_as"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`charged_as is missing from object`)

		return nil, diags
	}

	chargedAsVal, ok := chargedAsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`charged_as expected to be basetypes.StringValue, was: %T`, chargedAsAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return nil, diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	customPaymentFieldsEnabledAttribute, ok := attributes["custom_payment_fields_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_payment_fields_enabled is missing from object`)

		return nil, diags
	}

	customPaymentFieldsEnabledVal, ok := customPaymentFieldsEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_payment_fields_enabled expected to be basetypes.BoolValue, was: %T`, customPaymentFieldsEnabledAttribute))
	}

	hoursAttribute, ok := attributes["hours"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hours is missing from object`)

		return nil, diags
	}

	hoursVal, ok := hoursAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hours expected to be basetypes.Int64Value, was: %T`, hoursAttribute))
	}

	indexAttribute, ok := attributes["index"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`index is missing from object`)

		return nil, diags
	}

	indexVal, ok := indexAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`index expected to be basetypes.Int64Value, was: %T`, indexAttribute))
	}

	limitDownAttribute, ok := attributes["limit_down"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_down is missing from object`)

		return nil, diags
	}

	limitDownVal, ok := limitDownAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_down expected to be basetypes.Int64Value, was: %T`, limitDownAttribute))
	}

	limitOverwriteAttribute, ok := attributes["limit_overwrite"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_overwrite is missing from object`)

		return nil, diags
	}

	limitOverwriteVal, ok := limitOverwriteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_overwrite expected to be basetypes.BoolValue, was: %T`, limitOverwriteAttribute))
	}

	limitQuotaAttribute, ok := attributes["limit_quota"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_quota is missing from object`)

		return nil, diags
	}

	limitQuotaVal, ok := limitQuotaAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_quota expected to be basetypes.Int64Value, was: %T`, limitQuotaAttribute))
	}

	limitUpAttribute, ok := attributes["limit_up"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_up is missing from object`)

		return nil, diags
	}

	limitUpVal, ok := limitUpAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_up expected to be basetypes.Int64Value, was: %T`, limitUpAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	paymentFieldsAddressEnabledAttribute, ok := attributes["payment_fields_address_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_address_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsAddressEnabledVal, ok := paymentFieldsAddressEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_address_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsAddressEnabledAttribute))
	}

	paymentFieldsAddressRequiredAttribute, ok := attributes["payment_fields_address_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_address_required is missing from object`)

		return nil, diags
	}

	paymentFieldsAddressRequiredVal, ok := paymentFieldsAddressRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_address_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsAddressRequiredAttribute))
	}

	paymentFieldsCityEnabledAttribute, ok := attributes["payment_fields_city_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_city_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsCityEnabledVal, ok := paymentFieldsCityEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_city_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsCityEnabledAttribute))
	}

	paymentFieldsCityRequiredAttribute, ok := attributes["payment_fields_city_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_city_required is missing from object`)

		return nil, diags
	}

	paymentFieldsCityRequiredVal, ok := paymentFieldsCityRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_city_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsCityRequiredAttribute))
	}

	paymentFieldsCountryEnabledAttribute, ok := attributes["payment_fields_country_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_country_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsCountryEnabledVal, ok := paymentFieldsCountryEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_country_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsCountryEnabledAttribute))
	}

	paymentFieldsCountryRequiredAttribute, ok := attributes["payment_fields_country_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_country_required is missing from object`)

		return nil, diags
	}

	paymentFieldsCountryRequiredVal, ok := paymentFieldsCountryRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_country_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsCountryRequiredAttribute))
	}

	paymentFieldsEmailEnabledAttribute, ok := attributes["payment_fields_email_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_email_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsEmailEnabledVal, ok := paymentFieldsEmailEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_email_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsEmailEnabledAttribute))
	}

	paymentFieldsEmailRequiredAttribute, ok := attributes["payment_fields_email_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_email_required is missing from object`)

		return nil, diags
	}

	paymentFieldsEmailRequiredVal, ok := paymentFieldsEmailRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_email_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsEmailRequiredAttribute))
	}

	paymentFieldsFirstNameEnabledAttribute, ok := attributes["payment_fields_first_name_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_first_name_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsFirstNameEnabledVal, ok := paymentFieldsFirstNameEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_first_name_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsFirstNameEnabledAttribute))
	}

	paymentFieldsFirstNameRequiredAttribute, ok := attributes["payment_fields_first_name_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_first_name_required is missing from object`)

		return nil, diags
	}

	paymentFieldsFirstNameRequiredVal, ok := paymentFieldsFirstNameRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_first_name_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsFirstNameRequiredAttribute))
	}

	paymentFieldsLastNameEnabledAttribute, ok := attributes["payment_fields_last_name_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_last_name_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsLastNameEnabledVal, ok := paymentFieldsLastNameEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_last_name_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsLastNameEnabledAttribute))
	}

	paymentFieldsLastNameRequiredAttribute, ok := attributes["payment_fields_last_name_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_last_name_required is missing from object`)

		return nil, diags
	}

	paymentFieldsLastNameRequiredVal, ok := paymentFieldsLastNameRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_last_name_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsLastNameRequiredAttribute))
	}

	paymentFieldsStateEnabledAttribute, ok := attributes["payment_fields_state_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_state_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsStateEnabledVal, ok := paymentFieldsStateEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_state_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsStateEnabledAttribute))
	}

	paymentFieldsStateRequiredAttribute, ok := attributes["payment_fields_state_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_state_required is missing from object`)

		return nil, diags
	}

	paymentFieldsStateRequiredVal, ok := paymentFieldsStateRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_state_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsStateRequiredAttribute))
	}

	paymentFieldsZipEnabledAttribute, ok := attributes["payment_fields_zip_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_zip_enabled is missing from object`)

		return nil, diags
	}

	paymentFieldsZipEnabledVal, ok := paymentFieldsZipEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_zip_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsZipEnabledAttribute))
	}

	paymentFieldsZipRequiredAttribute, ok := attributes["payment_fields_zip_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_zip_required is missing from object`)

		return nil, diags
	}

	paymentFieldsZipRequiredVal, ok := paymentFieldsZipRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_zip_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsZipRequiredAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return nil, diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	trialDurationMinutesAttribute, ok := attributes["trial_duration_minutes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trial_duration_minutes is missing from object`)

		return nil, diags
	}

	trialDurationMinutesVal, ok := trialDurationMinutesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trial_duration_minutes expected to be basetypes.Int64Value, was: %T`, trialDurationMinutesAttribute))
	}

	trialResetAttribute, ok := attributes["trial_reset"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trial_reset is missing from object`)

		return nil, diags
	}

	trialResetVal, ok := trialResetAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trial_reset expected to be basetypes.NumberValue, was: %T`, trialResetAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Id:                             idVal,
		Amount:                         amountVal,
		AttrHidden:                     attrHiddenVal,
		AttrHiddenId:                   attrHiddenIdVal,
		AttrNoDelete:                   attrNoDeleteVal,
		AttrNoEdit:                     attrNoEditVal,
		ChargedAs:                      chargedAsVal,
		Currency:                       currencyVal,
		CustomPaymentFieldsEnabled:     customPaymentFieldsEnabledVal,
		Hours:                          hoursVal,
		Index:                          indexVal,
		LimitDown:                      limitDownVal,
		LimitOverwrite:                 limitOverwriteVal,
		LimitQuota:                     limitQuotaVal,
		LimitUp:                        limitUpVal,
		Name:                           nameVal,
		PaymentFieldsAddressEnabled:    paymentFieldsAddressEnabledVal,
		PaymentFieldsAddressRequired:   paymentFieldsAddressRequiredVal,
		PaymentFieldsCityEnabled:       paymentFieldsCityEnabledVal,
		PaymentFieldsCityRequired:      paymentFieldsCityRequiredVal,
		PaymentFieldsCountryEnabled:    paymentFieldsCountryEnabledVal,
		PaymentFieldsCountryRequired:   paymentFieldsCountryRequiredVal,
		PaymentFieldsEmailEnabled:      paymentFieldsEmailEnabledVal,
		PaymentFieldsEmailRequired:     paymentFieldsEmailRequiredVal,
		PaymentFieldsFirstNameEnabled:  paymentFieldsFirstNameEnabledVal,
		PaymentFieldsFirstNameRequired: paymentFieldsFirstNameRequiredVal,
		PaymentFieldsLastNameEnabled:   paymentFieldsLastNameEnabledVal,
		PaymentFieldsLastNameRequired:  paymentFieldsLastNameRequiredVal,
		PaymentFieldsStateEnabled:      paymentFieldsStateEnabledVal,
		PaymentFieldsStateRequired:     paymentFieldsStateRequiredVal,
		PaymentFieldsZipEnabled:        paymentFieldsZipEnabledVal,
		PaymentFieldsZipRequired:       paymentFieldsZipRequiredVal,
		SiteId:                         siteIdVal,
		TrialDurationMinutes:           trialDurationMinutesVal,
		TrialReset:                     trialResetVal,
		state:                          attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return NewDataValueUnknown(), diags
	}

	amountVal, ok := amountAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.NumberValue, was: %T`, amountAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	chargedAsAttribute, ok := attributes["charged_as"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`charged_as is missing from object`)

		return NewDataValueUnknown(), diags
	}

	chargedAsVal, ok := chargedAsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`charged_as expected to be basetypes.StringValue, was: %T`, chargedAsAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return NewDataValueUnknown(), diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	customPaymentFieldsEnabledAttribute, ok := attributes["custom_payment_fields_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_payment_fields_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	customPaymentFieldsEnabledVal, ok := customPaymentFieldsEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_payment_fields_enabled expected to be basetypes.BoolValue, was: %T`, customPaymentFieldsEnabledAttribute))
	}

	hoursAttribute, ok := attributes["hours"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hours is missing from object`)

		return NewDataValueUnknown(), diags
	}

	hoursVal, ok := hoursAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hours expected to be basetypes.Int64Value, was: %T`, hoursAttribute))
	}

	indexAttribute, ok := attributes["index"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`index is missing from object`)

		return NewDataValueUnknown(), diags
	}

	indexVal, ok := indexAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`index expected to be basetypes.Int64Value, was: %T`, indexAttribute))
	}

	limitDownAttribute, ok := attributes["limit_down"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_down is missing from object`)

		return NewDataValueUnknown(), diags
	}

	limitDownVal, ok := limitDownAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_down expected to be basetypes.Int64Value, was: %T`, limitDownAttribute))
	}

	limitOverwriteAttribute, ok := attributes["limit_overwrite"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_overwrite is missing from object`)

		return NewDataValueUnknown(), diags
	}

	limitOverwriteVal, ok := limitOverwriteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_overwrite expected to be basetypes.BoolValue, was: %T`, limitOverwriteAttribute))
	}

	limitQuotaAttribute, ok := attributes["limit_quota"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_quota is missing from object`)

		return NewDataValueUnknown(), diags
	}

	limitQuotaVal, ok := limitQuotaAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_quota expected to be basetypes.Int64Value, was: %T`, limitQuotaAttribute))
	}

	limitUpAttribute, ok := attributes["limit_up"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`limit_up is missing from object`)

		return NewDataValueUnknown(), diags
	}

	limitUpVal, ok := limitUpAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`limit_up expected to be basetypes.Int64Value, was: %T`, limitUpAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	paymentFieldsAddressEnabledAttribute, ok := attributes["payment_fields_address_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_address_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsAddressEnabledVal, ok := paymentFieldsAddressEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_address_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsAddressEnabledAttribute))
	}

	paymentFieldsAddressRequiredAttribute, ok := attributes["payment_fields_address_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_address_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsAddressRequiredVal, ok := paymentFieldsAddressRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_address_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsAddressRequiredAttribute))
	}

	paymentFieldsCityEnabledAttribute, ok := attributes["payment_fields_city_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_city_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsCityEnabledVal, ok := paymentFieldsCityEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_city_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsCityEnabledAttribute))
	}

	paymentFieldsCityRequiredAttribute, ok := attributes["payment_fields_city_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_city_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsCityRequiredVal, ok := paymentFieldsCityRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_city_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsCityRequiredAttribute))
	}

	paymentFieldsCountryEnabledAttribute, ok := attributes["payment_fields_country_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_country_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsCountryEnabledVal, ok := paymentFieldsCountryEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_country_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsCountryEnabledAttribute))
	}

	paymentFieldsCountryRequiredAttribute, ok := attributes["payment_fields_country_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_country_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsCountryRequiredVal, ok := paymentFieldsCountryRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_country_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsCountryRequiredAttribute))
	}

	paymentFieldsEmailEnabledAttribute, ok := attributes["payment_fields_email_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_email_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsEmailEnabledVal, ok := paymentFieldsEmailEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_email_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsEmailEnabledAttribute))
	}

	paymentFieldsEmailRequiredAttribute, ok := attributes["payment_fields_email_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_email_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsEmailRequiredVal, ok := paymentFieldsEmailRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_email_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsEmailRequiredAttribute))
	}

	paymentFieldsFirstNameEnabledAttribute, ok := attributes["payment_fields_first_name_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_first_name_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsFirstNameEnabledVal, ok := paymentFieldsFirstNameEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_first_name_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsFirstNameEnabledAttribute))
	}

	paymentFieldsFirstNameRequiredAttribute, ok := attributes["payment_fields_first_name_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_first_name_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsFirstNameRequiredVal, ok := paymentFieldsFirstNameRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_first_name_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsFirstNameRequiredAttribute))
	}

	paymentFieldsLastNameEnabledAttribute, ok := attributes["payment_fields_last_name_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_last_name_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsLastNameEnabledVal, ok := paymentFieldsLastNameEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_last_name_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsLastNameEnabledAttribute))
	}

	paymentFieldsLastNameRequiredAttribute, ok := attributes["payment_fields_last_name_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_last_name_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsLastNameRequiredVal, ok := paymentFieldsLastNameRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_last_name_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsLastNameRequiredAttribute))
	}

	paymentFieldsStateEnabledAttribute, ok := attributes["payment_fields_state_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_state_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsStateEnabledVal, ok := paymentFieldsStateEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_state_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsStateEnabledAttribute))
	}

	paymentFieldsStateRequiredAttribute, ok := attributes["payment_fields_state_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_state_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsStateRequiredVal, ok := paymentFieldsStateRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_state_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsStateRequiredAttribute))
	}

	paymentFieldsZipEnabledAttribute, ok := attributes["payment_fields_zip_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_zip_enabled is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsZipEnabledVal, ok := paymentFieldsZipEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_zip_enabled expected to be basetypes.BoolValue, was: %T`, paymentFieldsZipEnabledAttribute))
	}

	paymentFieldsZipRequiredAttribute, ok := attributes["payment_fields_zip_required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`payment_fields_zip_required is missing from object`)

		return NewDataValueUnknown(), diags
	}

	paymentFieldsZipRequiredVal, ok := paymentFieldsZipRequiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`payment_fields_zip_required expected to be basetypes.BoolValue, was: %T`, paymentFieldsZipRequiredAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	trialDurationMinutesAttribute, ok := attributes["trial_duration_minutes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trial_duration_minutes is missing from object`)

		return NewDataValueUnknown(), diags
	}

	trialDurationMinutesVal, ok := trialDurationMinutesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trial_duration_minutes expected to be basetypes.Int64Value, was: %T`, trialDurationMinutesAttribute))
	}

	trialResetAttribute, ok := attributes["trial_reset"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trial_reset is missing from object`)

		return NewDataValueUnknown(), diags
	}

	trialResetVal, ok := trialResetAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trial_reset expected to be basetypes.NumberValue, was: %T`, trialResetAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Id:                             idVal,
		Amount:                         amountVal,
		AttrHidden:                     attrHiddenVal,
		AttrHiddenId:                   attrHiddenIdVal,
		AttrNoDelete:                   attrNoDeleteVal,
		AttrNoEdit:                     attrNoEditVal,
		ChargedAs:                      chargedAsVal,
		Currency:                       currencyVal,
		CustomPaymentFieldsEnabled:     customPaymentFieldsEnabledVal,
		Hours:                          hoursVal,
		Index:                          indexVal,
		LimitDown:                      limitDownVal,
		LimitOverwrite:                 limitOverwriteVal,
		LimitQuota:                     limitQuotaVal,
		LimitUp:                        limitUpVal,
		Name:                           nameVal,
		PaymentFieldsAddressEnabled:    paymentFieldsAddressEnabledVal,
		PaymentFieldsAddressRequired:   paymentFieldsAddressRequiredVal,
		PaymentFieldsCityEnabled:       paymentFieldsCityEnabledVal,
		PaymentFieldsCityRequired:      paymentFieldsCityRequiredVal,
		PaymentFieldsCountryEnabled:    paymentFieldsCountryEnabledVal,
		PaymentFieldsCountryRequired:   paymentFieldsCountryRequiredVal,
		PaymentFieldsEmailEnabled:      paymentFieldsEmailEnabledVal,
		PaymentFieldsEmailRequired:     paymentFieldsEmailRequiredVal,
		PaymentFieldsFirstNameEnabled:  paymentFieldsFirstNameEnabledVal,
		PaymentFieldsFirstNameRequired: paymentFieldsFirstNameRequiredVal,
		PaymentFieldsLastNameEnabled:   paymentFieldsLastNameEnabledVal,
		PaymentFieldsLastNameRequired:  paymentFieldsLastNameRequiredVal,
		PaymentFieldsStateEnabled:      paymentFieldsStateEnabledVal,
		PaymentFieldsStateRequired:     paymentFieldsStateRequiredVal,
		PaymentFieldsZipEnabled:        paymentFieldsZipEnabledVal,
		PaymentFieldsZipRequired:       paymentFieldsZipRequiredVal,
		SiteId:                         siteIdVal,
		TrialDurationMinutes:           trialDurationMinutesVal,
		TrialReset:                     trialResetVal,
		state:                          attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Id                             basetypes.StringValue `tfsdk:"_id"`
	Amount                         basetypes.NumberValue `tfsdk:"amount"`
	AttrHidden                     basetypes.BoolValue   `tfsdk:"attr_hidden"`
	AttrHiddenId                   basetypes.StringValue `tfsdk:"attr_hidden_id"`
	AttrNoDelete                   basetypes.BoolValue   `tfsdk:"attr_no_delete"`
	AttrNoEdit                     basetypes.BoolValue   `tfsdk:"attr_no_edit"`
	ChargedAs                      basetypes.StringValue `tfsdk:"charged_as"`
	Currency                       basetypes.StringValue `tfsdk:"currency"`
	CustomPaymentFieldsEnabled     basetypes.BoolValue   `tfsdk:"custom_payment_fields_enabled"`
	Hours                          basetypes.Int64Value  `tfsdk:"hours"`
	Index                          basetypes.Int64Value  `tfsdk:"index"`
	LimitDown                      basetypes.Int64Value  `tfsdk:"limit_down"`
	LimitOverwrite                 basetypes.BoolValue   `tfsdk:"limit_overwrite"`
	LimitQuota                     basetypes.Int64Value  `tfsdk:"limit_quota"`
	LimitUp                        basetypes.Int64Value  `tfsdk:"limit_up"`
	Name                           basetypes.StringValue `tfsdk:"name"`
	PaymentFieldsAddressEnabled    basetypes.BoolValue   `tfsdk:"payment_fields_address_enabled"`
	PaymentFieldsAddressRequired   basetypes.BoolValue   `tfsdk:"payment_fields_address_required"`
	PaymentFieldsCityEnabled       basetypes.BoolValue   `tfsdk:"payment_fields_city_enabled"`
	PaymentFieldsCityRequired      basetypes.BoolValue   `tfsdk:"payment_fields_city_required"`
	PaymentFieldsCountryEnabled    basetypes.BoolValue   `tfsdk:"payment_fields_country_enabled"`
	PaymentFieldsCountryRequired   basetypes.BoolValue   `tfsdk:"payment_fields_country_required"`
	PaymentFieldsEmailEnabled      basetypes.BoolValue   `tfsdk:"payment_fields_email_enabled"`
	PaymentFieldsEmailRequired     basetypes.BoolValue   `tfsdk:"payment_fields_email_required"`
	PaymentFieldsFirstNameEnabled  basetypes.BoolValue   `tfsdk:"payment_fields_first_name_enabled"`
	PaymentFieldsFirstNameRequired basetypes.BoolValue   `tfsdk:"payment_fields_first_name_required"`
	PaymentFieldsLastNameEnabled   basetypes.BoolValue   `tfsdk:"payment_fields_last_name_enabled"`
	PaymentFieldsLastNameRequired  basetypes.BoolValue   `tfsdk:"payment_fields_last_name_required"`
	PaymentFieldsStateEnabled      basetypes.BoolValue   `tfsdk:"payment_fields_state_enabled"`
	PaymentFieldsStateRequired     basetypes.BoolValue   `tfsdk:"payment_fields_state_required"`
	PaymentFieldsZipEnabled        basetypes.BoolValue   `tfsdk:"payment_fields_zip_enabled"`
	PaymentFieldsZipRequired       basetypes.BoolValue   `tfsdk:"payment_fields_zip_required"`
	SiteId                         basetypes.StringValue `tfsdk:"site_id"`
	TrialDurationMinutes           basetypes.Int64Value  `tfsdk:"trial_duration_minutes"`
	TrialReset                     basetypes.NumberValue `tfsdk:"trial_reset"`
	state                          attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 35)

	var val tftypes.Value
	var err error

	attrTypes["_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["amount"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["attr_hidden"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_hidden_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_no_delete"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_no_edit"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["charged_as"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["currency"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["custom_payment_fields_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["hours"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["index"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["limit_down"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["limit_overwrite"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["limit_quota"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["limit_up"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["payment_fields_address_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_address_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_city_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_city_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_country_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_country_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_email_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_email_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_first_name_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_first_name_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_last_name_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_last_name_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_state_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_state_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_zip_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["payment_fields_zip_required"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["site_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["trial_duration_minutes"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["trial_reset"] = basetypes.NumberType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 35)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_id"] = val

		val, err = v.Amount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["amount"] = val

		val, err = v.AttrHidden.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden"] = val

		val, err = v.AttrHiddenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden_id"] = val

		val, err = v.AttrNoDelete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_delete"] = val

		val, err = v.AttrNoEdit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_edit"] = val

		val, err = v.ChargedAs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["charged_as"] = val

		val, err = v.Currency.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["currency"] = val

		val, err = v.CustomPaymentFieldsEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["custom_payment_fields_enabled"] = val

		val, err = v.Hours.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hours"] = val

		val, err = v.Index.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["index"] = val

		val, err = v.LimitDown.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["limit_down"] = val

		val, err = v.LimitOverwrite.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["limit_overwrite"] = val

		val, err = v.LimitQuota.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["limit_quota"] = val

		val, err = v.LimitUp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["limit_up"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.PaymentFieldsAddressEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_address_enabled"] = val

		val, err = v.PaymentFieldsAddressRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_address_required"] = val

		val, err = v.PaymentFieldsCityEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_city_enabled"] = val

		val, err = v.PaymentFieldsCityRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_city_required"] = val

		val, err = v.PaymentFieldsCountryEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_country_enabled"] = val

		val, err = v.PaymentFieldsCountryRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_country_required"] = val

		val, err = v.PaymentFieldsEmailEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_email_enabled"] = val

		val, err = v.PaymentFieldsEmailRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_email_required"] = val

		val, err = v.PaymentFieldsFirstNameEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_first_name_enabled"] = val

		val, err = v.PaymentFieldsFirstNameRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_first_name_required"] = val

		val, err = v.PaymentFieldsLastNameEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_last_name_enabled"] = val

		val, err = v.PaymentFieldsLastNameRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_last_name_required"] = val

		val, err = v.PaymentFieldsStateEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_state_enabled"] = val

		val, err = v.PaymentFieldsStateRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_state_required"] = val

		val, err = v.PaymentFieldsZipEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_zip_enabled"] = val

		val, err = v.PaymentFieldsZipRequired.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["payment_fields_zip_required"] = val

		val, err = v.SiteId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site_id"] = val

		val, err = v.TrialDurationMinutes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["trial_duration_minutes"] = val

		val, err = v.TrialReset.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["trial_reset"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"_id":                                basetypes.StringType{},
		"amount":                             basetypes.NumberType{},
		"attr_hidden":                        basetypes.BoolType{},
		"attr_hidden_id":                     basetypes.StringType{},
		"attr_no_delete":                     basetypes.BoolType{},
		"attr_no_edit":                       basetypes.BoolType{},
		"charged_as":                         basetypes.StringType{},
		"currency":                           basetypes.StringType{},
		"custom_payment_fields_enabled":      basetypes.BoolType{},
		"hours":                              basetypes.Int64Type{},
		"index":                              basetypes.Int64Type{},
		"limit_down":                         basetypes.Int64Type{},
		"limit_overwrite":                    basetypes.BoolType{},
		"limit_quota":                        basetypes.Int64Type{},
		"limit_up":                           basetypes.Int64Type{},
		"name":                               basetypes.StringType{},
		"payment_fields_address_enabled":     basetypes.BoolType{},
		"payment_fields_address_required":    basetypes.BoolType{},
		"payment_fields_city_enabled":        basetypes.BoolType{},
		"payment_fields_city_required":       basetypes.BoolType{},
		"payment_fields_country_enabled":     basetypes.BoolType{},
		"payment_fields_country_required":    basetypes.BoolType{},
		"payment_fields_email_enabled":       basetypes.BoolType{},
		"payment_fields_email_required":      basetypes.BoolType{},
		"payment_fields_first_name_enabled":  basetypes.BoolType{},
		"payment_fields_first_name_required": basetypes.BoolType{},
		"payment_fields_last_name_enabled":   basetypes.BoolType{},
		"payment_fields_last_name_required":  basetypes.BoolType{},
		"payment_fields_state_enabled":       basetypes.BoolType{},
		"payment_fields_state_required":      basetypes.BoolType{},
		"payment_fields_zip_enabled":         basetypes.BoolType{},
		"payment_fields_zip_required":        basetypes.BoolType{},
		"site_id":                            basetypes.StringType{},
		"trial_duration_minutes":             basetypes.Int64Type{},
		"trial_reset":                        basetypes.NumberType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_id":                                v.Id,
			"amount":                             v.Amount,
			"attr_hidden":                        v.AttrHidden,
			"attr_hidden_id":                     v.AttrHiddenId,
			"attr_no_delete":                     v.AttrNoDelete,
			"attr_no_edit":                       v.AttrNoEdit,
			"charged_as":                         v.ChargedAs,
			"currency":                           v.Currency,
			"custom_payment_fields_enabled":      v.CustomPaymentFieldsEnabled,
			"hours":                              v.Hours,
			"index":                              v.Index,
			"limit_down":                         v.LimitDown,
			"limit_overwrite":                    v.LimitOverwrite,
			"limit_quota":                        v.LimitQuota,
			"limit_up":                           v.LimitUp,
			"name":                               v.Name,
			"payment_fields_address_enabled":     v.PaymentFieldsAddressEnabled,
			"payment_fields_address_required":    v.PaymentFieldsAddressRequired,
			"payment_fields_city_enabled":        v.PaymentFieldsCityEnabled,
			"payment_fields_city_required":       v.PaymentFieldsCityRequired,
			"payment_fields_country_enabled":     v.PaymentFieldsCountryEnabled,
			"payment_fields_country_required":    v.PaymentFieldsCountryRequired,
			"payment_fields_email_enabled":       v.PaymentFieldsEmailEnabled,
			"payment_fields_email_required":      v.PaymentFieldsEmailRequired,
			"payment_fields_first_name_enabled":  v.PaymentFieldsFirstNameEnabled,
			"payment_fields_first_name_required": v.PaymentFieldsFirstNameRequired,
			"payment_fields_last_name_enabled":   v.PaymentFieldsLastNameEnabled,
			"payment_fields_last_name_required":  v.PaymentFieldsLastNameRequired,
			"payment_fields_state_enabled":       v.PaymentFieldsStateEnabled,
			"payment_fields_state_required":      v.PaymentFieldsStateRequired,
			"payment_fields_zip_enabled":         v.PaymentFieldsZipEnabled,
			"payment_fields_zip_required":        v.PaymentFieldsZipRequired,
			"site_id":                            v.SiteId,
			"trial_duration_minutes":             v.TrialDurationMinutes,
			"trial_reset":                        v.TrialReset,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Amount.Equal(other.Amount) {
		return false
	}

	if !v.AttrHidden.Equal(other.AttrHidden) {
		return false
	}

	if !v.AttrHiddenId.Equal(other.AttrHiddenId) {
		return false
	}

	if !v.AttrNoDelete.Equal(other.AttrNoDelete) {
		return false
	}

	if !v.AttrNoEdit.Equal(other.AttrNoEdit) {
		return false
	}

	if !v.ChargedAs.Equal(other.ChargedAs) {
		return false
	}

	if !v.Currency.Equal(other.Currency) {
		return false
	}

	if !v.CustomPaymentFieldsEnabled.Equal(other.CustomPaymentFieldsEnabled) {
		return false
	}

	if !v.Hours.Equal(other.Hours) {
		return false
	}

	if !v.Index.Equal(other.Index) {
		return false
	}

	if !v.LimitDown.Equal(other.LimitDown) {
		return false
	}

	if !v.LimitOverwrite.Equal(other.LimitOverwrite) {
		return false
	}

	if !v.LimitQuota.Equal(other.LimitQuota) {
		return false
	}

	if !v.LimitUp.Equal(other.LimitUp) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.PaymentFieldsAddressEnabled.Equal(other.PaymentFieldsAddressEnabled) {
		return false
	}

	if !v.PaymentFieldsAddressRequired.Equal(other.PaymentFieldsAddressRequired) {
		return false
	}

	if !v.PaymentFieldsCityEnabled.Equal(other.PaymentFieldsCityEnabled) {
		return false
	}

	if !v.PaymentFieldsCityRequired.Equal(other.PaymentFieldsCityRequired) {
		return false
	}

	if !v.PaymentFieldsCountryEnabled.Equal(other.PaymentFieldsCountryEnabled) {
		return false
	}

	if !v.PaymentFieldsCountryRequired.Equal(other.PaymentFieldsCountryRequired) {
		return false
	}

	if !v.PaymentFieldsEmailEnabled.Equal(other.PaymentFieldsEmailEnabled) {
		return false
	}

	if !v.PaymentFieldsEmailRequired.Equal(other.PaymentFieldsEmailRequired) {
		return false
	}

	if !v.PaymentFieldsFirstNameEnabled.Equal(other.PaymentFieldsFirstNameEnabled) {
		return false
	}

	if !v.PaymentFieldsFirstNameRequired.Equal(other.PaymentFieldsFirstNameRequired) {
		return false
	}

	if !v.PaymentFieldsLastNameEnabled.Equal(other.PaymentFieldsLastNameEnabled) {
		return false
	}

	if !v.PaymentFieldsLastNameRequired.Equal(other.PaymentFieldsLastNameRequired) {
		return false
	}

	if !v.PaymentFieldsStateEnabled.Equal(other.PaymentFieldsStateEnabled) {
		return false
	}

	if !v.PaymentFieldsStateRequired.Equal(other.PaymentFieldsStateRequired) {
		return false
	}

	if !v.PaymentFieldsZipEnabled.Equal(other.PaymentFieldsZipEnabled) {
		return false
	}

	if !v.PaymentFieldsZipRequired.Equal(other.PaymentFieldsZipRequired) {
		return false
	}

	if !v.SiteId.Equal(other.SiteId) {
		return false
	}

	if !v.TrialDurationMinutes.Equal(other.TrialDurationMinutes) {
		return false
	}

	if !v.TrialReset.Equal(other.TrialReset) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_id":                                basetypes.StringType{},
		"amount":                             basetypes.NumberType{},
		"attr_hidden":                        basetypes.BoolType{},
		"attr_hidden_id":                     basetypes.StringType{},
		"attr_no_delete":                     basetypes.BoolType{},
		"attr_no_edit":                       basetypes.BoolType{},
		"charged_as":                         basetypes.StringType{},
		"currency":                           basetypes.StringType{},
		"custom_payment_fields_enabled":      basetypes.BoolType{},
		"hours":                              basetypes.Int64Type{},
		"index":                              basetypes.Int64Type{},
		"limit_down":                         basetypes.Int64Type{},
		"limit_overwrite":                    basetypes.BoolType{},
		"limit_quota":                        basetypes.Int64Type{},
		"limit_up":                           basetypes.Int64Type{},
		"name":                               basetypes.StringType{},
		"payment_fields_address_enabled":     basetypes.BoolType{},
		"payment_fields_address_required":    basetypes.BoolType{},
		"payment_fields_city_enabled":        basetypes.BoolType{},
		"payment_fields_city_required":       basetypes.BoolType{},
		"payment_fields_country_enabled":     basetypes.BoolType{},
		"payment_fields_country_required":    basetypes.BoolType{},
		"payment_fields_email_enabled":       basetypes.BoolType{},
		"payment_fields_email_required":      basetypes.BoolType{},
		"payment_fields_first_name_enabled":  basetypes.BoolType{},
		"payment_fields_first_name_required": basetypes.BoolType{},
		"payment_fields_last_name_enabled":   basetypes.BoolType{},
		"payment_fields_last_name_required":  basetypes.BoolType{},
		"payment_fields_state_enabled":       basetypes.BoolType{},
		"payment_fields_state_required":      basetypes.BoolType{},
		"payment_fields_zip_enabled":         basetypes.BoolType{},
		"payment_fields_zip_required":        basetypes.BoolType{},
		"site_id":                            basetypes.StringType{},
		"trial_duration_minutes":             basetypes.Int64Type{},
		"trial_reset":                        basetypes.NumberType{},
	}
}

var _ basetypes.ObjectTypable = MetaType{}

type MetaType struct {
	basetypes.ObjectType
}

func (t MetaType) Equal(o attr.Type) bool {
	other, ok := o.(MetaType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetaType) String() string {
	return "MetaType"
}

func (t MetaType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return nil, diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueNull() MetaValue {
	return MetaValue{
		state: attr.ValueStateNull,
	}
}

func NewMetaValueUnknown() MetaValue {
	return MetaValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetaValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetaValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetaValue Attribute Value",
				"While creating a MetaValue value, a missing attribute value was detected. "+
					"A MetaValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetaValue Attribute Type",
				"While creating a MetaValue value, an invalid attribute value was detected. "+
					"A MetaValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetaValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetaValue Attribute Value",
				"While creating a MetaValue value, an extra attribute value was detected. "+
					"A MetaValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetaValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetaValue {
	object, diags := NewMetaValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetaValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetaType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetaValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetaValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetaValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetaValueMust(MetaValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetaType) ValueType(ctx context.Context) attr.Value {
	return MetaValue{}
}

var _ basetypes.ObjectValuable = MetaValue{}

type MetaValue struct {
	Msg   basetypes.StringValue `tfsdk:"msg"`
	Rc    basetypes.StringValue `tfsdk:"rc"`
	state attr.ValueState
}

func (v MetaValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rc"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.Rc.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rc"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetaValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetaValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetaValue) String() string {
	return "MetaValue"
}

func (v MetaValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"msg": v.Msg,
			"rc":  v.Rc,
		})

	return objVal, diags
}

func (v MetaValue) Equal(o attr.Value) bool {
	other, ok := o.(MetaValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.Rc.Equal(other.Rc) {
		return false
	}

	return true
}

func (v MetaValue) Type(ctx context.Context) attr.Type {
	return MetaType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetaValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}
}
