// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AccountDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_hidden": schema.BoolAttribute{
							Computed: true,
						},
						"attr_hidden_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_no_delete": schema.BoolAttribute{
							Computed: true,
						},
						"attr_no_edit": schema.BoolAttribute{
							Computed: true,
						},
						"filter_ids": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"ip": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"networkconf_id": schema.StringAttribute{
							Computed: true,
						},
						"site_id": schema.StringAttribute{
							Computed: true,
						},
						"tunnel_config_type": schema.StringAttribute{
							Computed: true,
						},
						"tunnel_medium_type": schema.Int64Attribute{
							Computed: true,
						},
						"tunnel_type": schema.Int64Attribute{
							Computed: true,
						},
						"ulp_user_id": schema.StringAttribute{
							Computed: true,
						},
						"vlan": schema.Int64Attribute{
							Computed: true,
						},
						"x_password": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"meta": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"msg": schema.StringAttribute{
						Computed: true,
					},
					"rc": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetaType{
					ObjectType: types.ObjectType{
						AttrTypes: MetaValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type AccountModel struct {
	Data types.List   `tfsdk:"data"`
	Id   types.String `tfsdk:"id"`
	Meta MetaValue    `tfsdk:"meta"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return nil, diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return nil, diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return nil, diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return nil, diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	filterIdsAttribute, ok := attributes["filter_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter_ids is missing from object`)

		return nil, diags
	}

	filterIdsVal, ok := filterIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter_ids expected to be basetypes.ListValue, was: %T`, filterIdsAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return nil, diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	networkconfIdAttribute, ok := attributes["networkconf_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`networkconf_id is missing from object`)

		return nil, diags
	}

	networkconfIdVal, ok := networkconfIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`networkconf_id expected to be basetypes.StringValue, was: %T`, networkconfIdAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return nil, diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	tunnelConfigTypeAttribute, ok := attributes["tunnel_config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_config_type is missing from object`)

		return nil, diags
	}

	tunnelConfigTypeVal, ok := tunnelConfigTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_config_type expected to be basetypes.StringValue, was: %T`, tunnelConfigTypeAttribute))
	}

	tunnelMediumTypeAttribute, ok := attributes["tunnel_medium_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_medium_type is missing from object`)

		return nil, diags
	}

	tunnelMediumTypeVal, ok := tunnelMediumTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_medium_type expected to be basetypes.Int64Value, was: %T`, tunnelMediumTypeAttribute))
	}

	tunnelTypeAttribute, ok := attributes["tunnel_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_type is missing from object`)

		return nil, diags
	}

	tunnelTypeVal, ok := tunnelTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_type expected to be basetypes.Int64Value, was: %T`, tunnelTypeAttribute))
	}

	ulpUserIdAttribute, ok := attributes["ulp_user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ulp_user_id is missing from object`)

		return nil, diags
	}

	ulpUserIdVal, ok := ulpUserIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ulp_user_id expected to be basetypes.StringValue, was: %T`, ulpUserIdAttribute))
	}

	vlanAttribute, ok := attributes["vlan"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vlan is missing from object`)

		return nil, diags
	}

	vlanVal, ok := vlanAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vlan expected to be basetypes.Int64Value, was: %T`, vlanAttribute))
	}

	xPasswordAttribute, ok := attributes["x_password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x_password is missing from object`)

		return nil, diags
	}

	xPasswordVal, ok := xPasswordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x_password expected to be basetypes.StringValue, was: %T`, xPasswordAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Id:               idVal,
		AttrHidden:       attrHiddenVal,
		AttrHiddenId:     attrHiddenIdVal,
		AttrNoDelete:     attrNoDeleteVal,
		AttrNoEdit:       attrNoEditVal,
		FilterIds:        filterIdsVal,
		Ip:               ipVal,
		Name:             nameVal,
		NetworkconfId:    networkconfIdVal,
		SiteId:           siteIdVal,
		TunnelConfigType: tunnelConfigTypeVal,
		TunnelMediumType: tunnelMediumTypeVal,
		TunnelType:       tunnelTypeVal,
		UlpUserId:        ulpUserIdVal,
		Vlan:             vlanVal,
		XPassword:        xPasswordVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	filterIdsAttribute, ok := attributes["filter_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter_ids is missing from object`)

		return NewDataValueUnknown(), diags
	}

	filterIdsVal, ok := filterIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter_ids expected to be basetypes.ListValue, was: %T`, filterIdsAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return NewDataValueUnknown(), diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	networkconfIdAttribute, ok := attributes["networkconf_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`networkconf_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	networkconfIdVal, ok := networkconfIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`networkconf_id expected to be basetypes.StringValue, was: %T`, networkconfIdAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	tunnelConfigTypeAttribute, ok := attributes["tunnel_config_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_config_type is missing from object`)

		return NewDataValueUnknown(), diags
	}

	tunnelConfigTypeVal, ok := tunnelConfigTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_config_type expected to be basetypes.StringValue, was: %T`, tunnelConfigTypeAttribute))
	}

	tunnelMediumTypeAttribute, ok := attributes["tunnel_medium_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_medium_type is missing from object`)

		return NewDataValueUnknown(), diags
	}

	tunnelMediumTypeVal, ok := tunnelMediumTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_medium_type expected to be basetypes.Int64Value, was: %T`, tunnelMediumTypeAttribute))
	}

	tunnelTypeAttribute, ok := attributes["tunnel_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_type is missing from object`)

		return NewDataValueUnknown(), diags
	}

	tunnelTypeVal, ok := tunnelTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_type expected to be basetypes.Int64Value, was: %T`, tunnelTypeAttribute))
	}

	ulpUserIdAttribute, ok := attributes["ulp_user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ulp_user_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	ulpUserIdVal, ok := ulpUserIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ulp_user_id expected to be basetypes.StringValue, was: %T`, ulpUserIdAttribute))
	}

	vlanAttribute, ok := attributes["vlan"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vlan is missing from object`)

		return NewDataValueUnknown(), diags
	}

	vlanVal, ok := vlanAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vlan expected to be basetypes.Int64Value, was: %T`, vlanAttribute))
	}

	xPasswordAttribute, ok := attributes["x_password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x_password is missing from object`)

		return NewDataValueUnknown(), diags
	}

	xPasswordVal, ok := xPasswordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x_password expected to be basetypes.StringValue, was: %T`, xPasswordAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Id:               idVal,
		AttrHidden:       attrHiddenVal,
		AttrHiddenId:     attrHiddenIdVal,
		AttrNoDelete:     attrNoDeleteVal,
		AttrNoEdit:       attrNoEditVal,
		FilterIds:        filterIdsVal,
		Ip:               ipVal,
		Name:             nameVal,
		NetworkconfId:    networkconfIdVal,
		SiteId:           siteIdVal,
		TunnelConfigType: tunnelConfigTypeVal,
		TunnelMediumType: tunnelMediumTypeVal,
		TunnelType:       tunnelTypeVal,
		UlpUserId:        ulpUserIdVal,
		Vlan:             vlanVal,
		XPassword:        xPasswordVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Id               basetypes.StringValue `tfsdk:"_id"`
	AttrHidden       basetypes.BoolValue   `tfsdk:"attr_hidden"`
	AttrHiddenId     basetypes.StringValue `tfsdk:"attr_hidden_id"`
	AttrNoDelete     basetypes.BoolValue   `tfsdk:"attr_no_delete"`
	AttrNoEdit       basetypes.BoolValue   `tfsdk:"attr_no_edit"`
	FilterIds        basetypes.ListValue   `tfsdk:"filter_ids"`
	Ip               basetypes.StringValue `tfsdk:"ip"`
	Name             basetypes.StringValue `tfsdk:"name"`
	NetworkconfId    basetypes.StringValue `tfsdk:"networkconf_id"`
	SiteId           basetypes.StringValue `tfsdk:"site_id"`
	TunnelConfigType basetypes.StringValue `tfsdk:"tunnel_config_type"`
	TunnelMediumType basetypes.Int64Value  `tfsdk:"tunnel_medium_type"`
	TunnelType       basetypes.Int64Value  `tfsdk:"tunnel_type"`
	UlpUserId        basetypes.StringValue `tfsdk:"ulp_user_id"`
	Vlan             basetypes.Int64Value  `tfsdk:"vlan"`
	XPassword        basetypes.StringValue `tfsdk:"x_password"`
	state            attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 16)

	var val tftypes.Value
	var err error

	attrTypes["_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_hidden"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_hidden_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_no_delete"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_no_edit"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["filter_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["networkconf_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["site_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tunnel_config_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tunnel_medium_type"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["tunnel_type"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["ulp_user_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vlan"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["x_password"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 16)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_id"] = val

		val, err = v.AttrHidden.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden"] = val

		val, err = v.AttrHiddenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden_id"] = val

		val, err = v.AttrNoDelete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_delete"] = val

		val, err = v.AttrNoEdit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_edit"] = val

		val, err = v.FilterIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["filter_ids"] = val

		val, err = v.Ip.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.NetworkconfId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["networkconf_id"] = val

		val, err = v.SiteId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site_id"] = val

		val, err = v.TunnelConfigType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tunnel_config_type"] = val

		val, err = v.TunnelMediumType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tunnel_medium_type"] = val

		val, err = v.TunnelType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tunnel_type"] = val

		val, err = v.UlpUserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ulp_user_id"] = val

		val, err = v.Vlan.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vlan"] = val

		val, err = v.XPassword.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["x_password"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var filterIdsVal basetypes.ListValue
	switch {
	case v.FilterIds.IsUnknown():
		filterIdsVal = types.ListUnknown(types.StringType)
	case v.FilterIds.IsNull():
		filterIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		filterIdsVal, d = types.ListValue(types.StringType, v.FilterIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"_id":            basetypes.StringType{},
			"attr_hidden":    basetypes.BoolType{},
			"attr_hidden_id": basetypes.StringType{},
			"attr_no_delete": basetypes.BoolType{},
			"attr_no_edit":   basetypes.BoolType{},
			"filter_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"ip":                 basetypes.StringType{},
			"name":               basetypes.StringType{},
			"networkconf_id":     basetypes.StringType{},
			"site_id":            basetypes.StringType{},
			"tunnel_config_type": basetypes.StringType{},
			"tunnel_medium_type": basetypes.Int64Type{},
			"tunnel_type":        basetypes.Int64Type{},
			"ulp_user_id":        basetypes.StringType{},
			"vlan":               basetypes.Int64Type{},
			"x_password":         basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"filter_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"ip":                 basetypes.StringType{},
		"name":               basetypes.StringType{},
		"networkconf_id":     basetypes.StringType{},
		"site_id":            basetypes.StringType{},
		"tunnel_config_type": basetypes.StringType{},
		"tunnel_medium_type": basetypes.Int64Type{},
		"tunnel_type":        basetypes.Int64Type{},
		"ulp_user_id":        basetypes.StringType{},
		"vlan":               basetypes.Int64Type{},
		"x_password":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_id":                v.Id,
			"attr_hidden":        v.AttrHidden,
			"attr_hidden_id":     v.AttrHiddenId,
			"attr_no_delete":     v.AttrNoDelete,
			"attr_no_edit":       v.AttrNoEdit,
			"filter_ids":         filterIdsVal,
			"ip":                 v.Ip,
			"name":               v.Name,
			"networkconf_id":     v.NetworkconfId,
			"site_id":            v.SiteId,
			"tunnel_config_type": v.TunnelConfigType,
			"tunnel_medium_type": v.TunnelMediumType,
			"tunnel_type":        v.TunnelType,
			"ulp_user_id":        v.UlpUserId,
			"vlan":               v.Vlan,
			"x_password":         v.XPassword,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.AttrHidden.Equal(other.AttrHidden) {
		return false
	}

	if !v.AttrHiddenId.Equal(other.AttrHiddenId) {
		return false
	}

	if !v.AttrNoDelete.Equal(other.AttrNoDelete) {
		return false
	}

	if !v.AttrNoEdit.Equal(other.AttrNoEdit) {
		return false
	}

	if !v.FilterIds.Equal(other.FilterIds) {
		return false
	}

	if !v.Ip.Equal(other.Ip) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.NetworkconfId.Equal(other.NetworkconfId) {
		return false
	}

	if !v.SiteId.Equal(other.SiteId) {
		return false
	}

	if !v.TunnelConfigType.Equal(other.TunnelConfigType) {
		return false
	}

	if !v.TunnelMediumType.Equal(other.TunnelMediumType) {
		return false
	}

	if !v.TunnelType.Equal(other.TunnelType) {
		return false
	}

	if !v.UlpUserId.Equal(other.UlpUserId) {
		return false
	}

	if !v.Vlan.Equal(other.Vlan) {
		return false
	}

	if !v.XPassword.Equal(other.XPassword) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"filter_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"ip":                 basetypes.StringType{},
		"name":               basetypes.StringType{},
		"networkconf_id":     basetypes.StringType{},
		"site_id":            basetypes.StringType{},
		"tunnel_config_type": basetypes.StringType{},
		"tunnel_medium_type": basetypes.Int64Type{},
		"tunnel_type":        basetypes.Int64Type{},
		"ulp_user_id":        basetypes.StringType{},
		"vlan":               basetypes.Int64Type{},
		"x_password":         basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = MetaType{}

type MetaType struct {
	basetypes.ObjectType
}

func (t MetaType) Equal(o attr.Type) bool {
	other, ok := o.(MetaType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetaType) String() string {
	return "MetaType"
}

func (t MetaType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return nil, diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueNull() MetaValue {
	return MetaValue{
		state: attr.ValueStateNull,
	}
}

func NewMetaValueUnknown() MetaValue {
	return MetaValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetaValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetaValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetaValue Attribute Value",
				"While creating a MetaValue value, a missing attribute value was detected. "+
					"A MetaValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetaValue Attribute Type",
				"While creating a MetaValue value, an invalid attribute value was detected. "+
					"A MetaValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetaValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetaValue Attribute Value",
				"While creating a MetaValue value, an extra attribute value was detected. "+
					"A MetaValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetaValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetaValue {
	object, diags := NewMetaValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetaValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetaType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetaValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetaValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetaValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetaValueMust(MetaValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetaType) ValueType(ctx context.Context) attr.Value {
	return MetaValue{}
}

var _ basetypes.ObjectValuable = MetaValue{}

type MetaValue struct {
	Msg   basetypes.StringValue `tfsdk:"msg"`
	Rc    basetypes.StringValue `tfsdk:"rc"`
	state attr.ValueState
}

func (v MetaValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rc"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.Rc.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rc"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetaValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetaValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetaValue) String() string {
	return "MetaValue"
}

func (v MetaValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"msg": v.Msg,
			"rc":  v.Rc,
		})

	return objVal, diags
}

func (v MetaValue) Equal(o attr.Value) bool {
	other, ok := o.(MetaValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.Rc.Equal(other.Rc) {
		return false
	}

	return true
}

func (v MetaValue) Type(ctx context.Context) attr.Type {
	return MetaType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetaValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}
}
