// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DynamicDnsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_hidden": schema.BoolAttribute{
							Computed: true,
						},
						"attr_hidden_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_no_delete": schema.BoolAttribute{
							Computed: true,
						},
						"attr_no_edit": schema.BoolAttribute{
							Computed: true,
						},
						"custom_service": schema.StringAttribute{
							Computed: true,
						},
						"host_name": schema.StringAttribute{
							Computed: true,
						},
						"interface": schema.StringAttribute{
							Computed: true,
						},
						"login": schema.StringAttribute{
							Computed: true,
						},
						"options": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"server": schema.StringAttribute{
							Computed: true,
						},
						"service": schema.StringAttribute{
							Computed: true,
						},
						"site_id": schema.StringAttribute{
							Computed: true,
						},
						"x_password": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"meta": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"msg": schema.StringAttribute{
						Computed: true,
					},
					"rc": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetaType{
					ObjectType: types.ObjectType{
						AttrTypes: MetaValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type DynamicDnsModel struct {
	Data types.List   `tfsdk:"data"`
	Id   types.String `tfsdk:"id"`
	Meta MetaValue    `tfsdk:"meta"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return nil, diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return nil, diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return nil, diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return nil, diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	customServiceAttribute, ok := attributes["custom_service"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_service is missing from object`)

		return nil, diags
	}

	customServiceVal, ok := customServiceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_service expected to be basetypes.StringValue, was: %T`, customServiceAttribute))
	}

	hostNameAttribute, ok := attributes["host_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`host_name is missing from object`)

		return nil, diags
	}

	hostNameVal, ok := hostNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`host_name expected to be basetypes.StringValue, was: %T`, hostNameAttribute))
	}

	interfaceAttribute, ok := attributes["interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface is missing from object`)

		return nil, diags
	}

	interfaceVal, ok := interfaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface expected to be basetypes.StringValue, was: %T`, interfaceAttribute))
	}

	loginAttribute, ok := attributes["login"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`login is missing from object`)

		return nil, diags
	}

	loginVal, ok := loginAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`login expected to be basetypes.StringValue, was: %T`, loginAttribute))
	}

	optionsAttribute, ok := attributes["options"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`options is missing from object`)

		return nil, diags
	}

	optionsVal, ok := optionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`options expected to be basetypes.ListValue, was: %T`, optionsAttribute))
	}

	serverAttribute, ok := attributes["server"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server is missing from object`)

		return nil, diags
	}

	serverVal, ok := serverAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server expected to be basetypes.StringValue, was: %T`, serverAttribute))
	}

	serviceAttribute, ok := attributes["service"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service is missing from object`)

		return nil, diags
	}

	serviceVal, ok := serviceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service expected to be basetypes.StringValue, was: %T`, serviceAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return nil, diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	xPasswordAttribute, ok := attributes["x_password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x_password is missing from object`)

		return nil, diags
	}

	xPasswordVal, ok := xPasswordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x_password expected to be basetypes.StringValue, was: %T`, xPasswordAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Id:            idVal,
		AttrHidden:    attrHiddenVal,
		AttrHiddenId:  attrHiddenIdVal,
		AttrNoDelete:  attrNoDeleteVal,
		AttrNoEdit:    attrNoEditVal,
		CustomService: customServiceVal,
		HostName:      hostNameVal,
		Interface:     interfaceVal,
		Login:         loginVal,
		Options:       optionsVal,
		Server:        serverVal,
		Service:       serviceVal,
		SiteId:        siteIdVal,
		XPassword:     xPasswordVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	customServiceAttribute, ok := attributes["custom_service"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_service is missing from object`)

		return NewDataValueUnknown(), diags
	}

	customServiceVal, ok := customServiceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_service expected to be basetypes.StringValue, was: %T`, customServiceAttribute))
	}

	hostNameAttribute, ok := attributes["host_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`host_name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	hostNameVal, ok := hostNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`host_name expected to be basetypes.StringValue, was: %T`, hostNameAttribute))
	}

	interfaceAttribute, ok := attributes["interface"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface is missing from object`)

		return NewDataValueUnknown(), diags
	}

	interfaceVal, ok := interfaceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface expected to be basetypes.StringValue, was: %T`, interfaceAttribute))
	}

	loginAttribute, ok := attributes["login"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`login is missing from object`)

		return NewDataValueUnknown(), diags
	}

	loginVal, ok := loginAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`login expected to be basetypes.StringValue, was: %T`, loginAttribute))
	}

	optionsAttribute, ok := attributes["options"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`options is missing from object`)

		return NewDataValueUnknown(), diags
	}

	optionsVal, ok := optionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`options expected to be basetypes.ListValue, was: %T`, optionsAttribute))
	}

	serverAttribute, ok := attributes["server"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server is missing from object`)

		return NewDataValueUnknown(), diags
	}

	serverVal, ok := serverAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server expected to be basetypes.StringValue, was: %T`, serverAttribute))
	}

	serviceAttribute, ok := attributes["service"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service is missing from object`)

		return NewDataValueUnknown(), diags
	}

	serviceVal, ok := serviceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service expected to be basetypes.StringValue, was: %T`, serviceAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	xPasswordAttribute, ok := attributes["x_password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x_password is missing from object`)

		return NewDataValueUnknown(), diags
	}

	xPasswordVal, ok := xPasswordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x_password expected to be basetypes.StringValue, was: %T`, xPasswordAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Id:            idVal,
		AttrHidden:    attrHiddenVal,
		AttrHiddenId:  attrHiddenIdVal,
		AttrNoDelete:  attrNoDeleteVal,
		AttrNoEdit:    attrNoEditVal,
		CustomService: customServiceVal,
		HostName:      hostNameVal,
		Interface:     interfaceVal,
		Login:         loginVal,
		Options:       optionsVal,
		Server:        serverVal,
		Service:       serviceVal,
		SiteId:        siteIdVal,
		XPassword:     xPasswordVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Id            basetypes.StringValue `tfsdk:"_id"`
	AttrHidden    basetypes.BoolValue   `tfsdk:"attr_hidden"`
	AttrHiddenId  basetypes.StringValue `tfsdk:"attr_hidden_id"`
	AttrNoDelete  basetypes.BoolValue   `tfsdk:"attr_no_delete"`
	AttrNoEdit    basetypes.BoolValue   `tfsdk:"attr_no_edit"`
	CustomService basetypes.StringValue `tfsdk:"custom_service"`
	HostName      basetypes.StringValue `tfsdk:"host_name"`
	Interface     basetypes.StringValue `tfsdk:"interface"`
	Login         basetypes.StringValue `tfsdk:"login"`
	Options       basetypes.ListValue   `tfsdk:"options"`
	Server        basetypes.StringValue `tfsdk:"server"`
	Service       basetypes.StringValue `tfsdk:"service"`
	SiteId        basetypes.StringValue `tfsdk:"site_id"`
	XPassword     basetypes.StringValue `tfsdk:"x_password"`
	state         attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 14)

	var val tftypes.Value
	var err error

	attrTypes["_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_hidden"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_hidden_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_no_delete"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_no_edit"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["custom_service"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["host_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["interface"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["login"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["options"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["server"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["service"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["site_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["x_password"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 14)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_id"] = val

		val, err = v.AttrHidden.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden"] = val

		val, err = v.AttrHiddenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden_id"] = val

		val, err = v.AttrNoDelete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_delete"] = val

		val, err = v.AttrNoEdit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_edit"] = val

		val, err = v.CustomService.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["custom_service"] = val

		val, err = v.HostName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["host_name"] = val

		val, err = v.Interface.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interface"] = val

		val, err = v.Login.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["login"] = val

		val, err = v.Options.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["options"] = val

		val, err = v.Server.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["server"] = val

		val, err = v.Service.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["service"] = val

		val, err = v.SiteId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site_id"] = val

		val, err = v.XPassword.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["x_password"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var optionsVal basetypes.ListValue
	switch {
	case v.Options.IsUnknown():
		optionsVal = types.ListUnknown(types.StringType)
	case v.Options.IsNull():
		optionsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		optionsVal, d = types.ListValue(types.StringType, v.Options.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"_id":            basetypes.StringType{},
			"attr_hidden":    basetypes.BoolType{},
			"attr_hidden_id": basetypes.StringType{},
			"attr_no_delete": basetypes.BoolType{},
			"attr_no_edit":   basetypes.BoolType{},
			"custom_service": basetypes.StringType{},
			"host_name":      basetypes.StringType{},
			"interface":      basetypes.StringType{},
			"login":          basetypes.StringType{},
			"options": basetypes.ListType{
				ElemType: types.StringType,
			},
			"server":     basetypes.StringType{},
			"service":    basetypes.StringType{},
			"site_id":    basetypes.StringType{},
			"x_password": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"custom_service": basetypes.StringType{},
		"host_name":      basetypes.StringType{},
		"interface":      basetypes.StringType{},
		"login":          basetypes.StringType{},
		"options": basetypes.ListType{
			ElemType: types.StringType,
		},
		"server":     basetypes.StringType{},
		"service":    basetypes.StringType{},
		"site_id":    basetypes.StringType{},
		"x_password": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_id":            v.Id,
			"attr_hidden":    v.AttrHidden,
			"attr_hidden_id": v.AttrHiddenId,
			"attr_no_delete": v.AttrNoDelete,
			"attr_no_edit":   v.AttrNoEdit,
			"custom_service": v.CustomService,
			"host_name":      v.HostName,
			"interface":      v.Interface,
			"login":          v.Login,
			"options":        optionsVal,
			"server":         v.Server,
			"service":        v.Service,
			"site_id":        v.SiteId,
			"x_password":     v.XPassword,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.AttrHidden.Equal(other.AttrHidden) {
		return false
	}

	if !v.AttrHiddenId.Equal(other.AttrHiddenId) {
		return false
	}

	if !v.AttrNoDelete.Equal(other.AttrNoDelete) {
		return false
	}

	if !v.AttrNoEdit.Equal(other.AttrNoEdit) {
		return false
	}

	if !v.CustomService.Equal(other.CustomService) {
		return false
	}

	if !v.HostName.Equal(other.HostName) {
		return false
	}

	if !v.Interface.Equal(other.Interface) {
		return false
	}

	if !v.Login.Equal(other.Login) {
		return false
	}

	if !v.Options.Equal(other.Options) {
		return false
	}

	if !v.Server.Equal(other.Server) {
		return false
	}

	if !v.Service.Equal(other.Service) {
		return false
	}

	if !v.SiteId.Equal(other.SiteId) {
		return false
	}

	if !v.XPassword.Equal(other.XPassword) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"custom_service": basetypes.StringType{},
		"host_name":      basetypes.StringType{},
		"interface":      basetypes.StringType{},
		"login":          basetypes.StringType{},
		"options": basetypes.ListType{
			ElemType: types.StringType,
		},
		"server":     basetypes.StringType{},
		"service":    basetypes.StringType{},
		"site_id":    basetypes.StringType{},
		"x_password": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = MetaType{}

type MetaType struct {
	basetypes.ObjectType
}

func (t MetaType) Equal(o attr.Type) bool {
	other, ok := o.(MetaType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetaType) String() string {
	return "MetaType"
}

func (t MetaType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return nil, diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueNull() MetaValue {
	return MetaValue{
		state: attr.ValueStateNull,
	}
}

func NewMetaValueUnknown() MetaValue {
	return MetaValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetaValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetaValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetaValue Attribute Value",
				"While creating a MetaValue value, a missing attribute value was detected. "+
					"A MetaValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetaValue Attribute Type",
				"While creating a MetaValue value, an invalid attribute value was detected. "+
					"A MetaValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetaValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetaValue Attribute Value",
				"While creating a MetaValue value, an extra attribute value was detected. "+
					"A MetaValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetaValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetaValue {
	object, diags := NewMetaValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetaValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetaType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetaValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetaValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetaValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetaValueMust(MetaValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetaType) ValueType(ctx context.Context) attr.Value {
	return MetaValue{}
}

var _ basetypes.ObjectValuable = MetaValue{}

type MetaValue struct {
	Msg   basetypes.StringValue `tfsdk:"msg"`
	Rc    basetypes.StringValue `tfsdk:"rc"`
	state attr.ValueState
}

func (v MetaValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rc"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.Rc.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rc"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetaValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetaValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetaValue) String() string {
	return "MetaValue"
}

func (v MetaValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"msg": v.Msg,
			"rc":  v.Rc,
		})

	return objVal, diags
}

func (v MetaValue) Equal(o attr.Value) bool {
	other, ok := o.(MetaValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.Rc.Equal(other.Rc) {
		return false
	}

	return true
}

func (v MetaValue) Type(ctx context.Context) attr.Type {
	return MetaType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetaValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}
}
