// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MapDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_hidden": schema.BoolAttribute{
							Computed: true,
						},
						"attr_hidden_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_no_delete": schema.BoolAttribute{
							Computed: true,
						},
						"attr_no_edit": schema.BoolAttribute{
							Computed: true,
						},
						"lat": schema.StringAttribute{
							Computed: true,
						},
						"lng": schema.StringAttribute{
							Computed: true,
						},
						"map_type_id": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"offset_left": schema.NumberAttribute{
							Computed: true,
						},
						"offset_top": schema.NumberAttribute{
							Computed: true,
						},
						"opacity": schema.NumberAttribute{
							Computed: true,
						},
						"selected": schema.BoolAttribute{
							Computed: true,
						},
						"site_id": schema.StringAttribute{
							Computed: true,
						},
						"tilt": schema.Int64Attribute{
							Computed: true,
						},
						"type": schema.StringAttribute{
							Computed: true,
						},
						"unit": schema.StringAttribute{
							Computed: true,
						},
						"upp": schema.NumberAttribute{
							Computed: true,
						},
						"zoom": schema.Int64Attribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"meta": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"msg": schema.StringAttribute{
						Computed: true,
					},
					"rc": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetaType{
					ObjectType: types.ObjectType{
						AttrTypes: MetaValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type MapModel struct {
	Data types.List   `tfsdk:"data"`
	Id   types.String `tfsdk:"id"`
	Meta MetaValue    `tfsdk:"meta"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return nil, diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return nil, diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return nil, diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return nil, diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	latAttribute, ok := attributes["lat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lat is missing from object`)

		return nil, diags
	}

	latVal, ok := latAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lat expected to be basetypes.StringValue, was: %T`, latAttribute))
	}

	lngAttribute, ok := attributes["lng"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lng is missing from object`)

		return nil, diags
	}

	lngVal, ok := lngAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lng expected to be basetypes.StringValue, was: %T`, lngAttribute))
	}

	mapTypeIdAttribute, ok := attributes["map_type_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`map_type_id is missing from object`)

		return nil, diags
	}

	mapTypeIdVal, ok := mapTypeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`map_type_id expected to be basetypes.StringValue, was: %T`, mapTypeIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	offsetLeftAttribute, ok := attributes["offset_left"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`offset_left is missing from object`)

		return nil, diags
	}

	offsetLeftVal, ok := offsetLeftAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`offset_left expected to be basetypes.NumberValue, was: %T`, offsetLeftAttribute))
	}

	offsetTopAttribute, ok := attributes["offset_top"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`offset_top is missing from object`)

		return nil, diags
	}

	offsetTopVal, ok := offsetTopAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`offset_top expected to be basetypes.NumberValue, was: %T`, offsetTopAttribute))
	}

	opacityAttribute, ok := attributes["opacity"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`opacity is missing from object`)

		return nil, diags
	}

	opacityVal, ok := opacityAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`opacity expected to be basetypes.NumberValue, was: %T`, opacityAttribute))
	}

	selectedAttribute, ok := attributes["selected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`selected is missing from object`)

		return nil, diags
	}

	selectedVal, ok := selectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`selected expected to be basetypes.BoolValue, was: %T`, selectedAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return nil, diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	tiltAttribute, ok := attributes["tilt"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tilt is missing from object`)

		return nil, diags
	}

	tiltVal, ok := tiltAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tilt expected to be basetypes.Int64Value, was: %T`, tiltAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	unitAttribute, ok := attributes["unit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unit is missing from object`)

		return nil, diags
	}

	unitVal, ok := unitAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unit expected to be basetypes.StringValue, was: %T`, unitAttribute))
	}

	uppAttribute, ok := attributes["upp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`upp is missing from object`)

		return nil, diags
	}

	uppVal, ok := uppAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`upp expected to be basetypes.NumberValue, was: %T`, uppAttribute))
	}

	zoomAttribute, ok := attributes["zoom"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zoom is missing from object`)

		return nil, diags
	}

	zoomVal, ok := zoomAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zoom expected to be basetypes.Int64Value, was: %T`, zoomAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Id:           idVal,
		AttrHidden:   attrHiddenVal,
		AttrHiddenId: attrHiddenIdVal,
		AttrNoDelete: attrNoDeleteVal,
		AttrNoEdit:   attrNoEditVal,
		Lat:          latVal,
		Lng:          lngVal,
		MapTypeId:    mapTypeIdVal,
		Name:         nameVal,
		OffsetLeft:   offsetLeftVal,
		OffsetTop:    offsetTopVal,
		Opacity:      opacityVal,
		Selected:     selectedVal,
		SiteId:       siteIdVal,
		Tilt:         tiltVal,
		DataType:     typeVal,
		Unit:         unitVal,
		Upp:          uppVal,
		Zoom:         zoomVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	latAttribute, ok := attributes["lat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lat is missing from object`)

		return NewDataValueUnknown(), diags
	}

	latVal, ok := latAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lat expected to be basetypes.StringValue, was: %T`, latAttribute))
	}

	lngAttribute, ok := attributes["lng"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lng is missing from object`)

		return NewDataValueUnknown(), diags
	}

	lngVal, ok := lngAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lng expected to be basetypes.StringValue, was: %T`, lngAttribute))
	}

	mapTypeIdAttribute, ok := attributes["map_type_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`map_type_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	mapTypeIdVal, ok := mapTypeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`map_type_id expected to be basetypes.StringValue, was: %T`, mapTypeIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	offsetLeftAttribute, ok := attributes["offset_left"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`offset_left is missing from object`)

		return NewDataValueUnknown(), diags
	}

	offsetLeftVal, ok := offsetLeftAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`offset_left expected to be basetypes.NumberValue, was: %T`, offsetLeftAttribute))
	}

	offsetTopAttribute, ok := attributes["offset_top"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`offset_top is missing from object`)

		return NewDataValueUnknown(), diags
	}

	offsetTopVal, ok := offsetTopAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`offset_top expected to be basetypes.NumberValue, was: %T`, offsetTopAttribute))
	}

	opacityAttribute, ok := attributes["opacity"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`opacity is missing from object`)

		return NewDataValueUnknown(), diags
	}

	opacityVal, ok := opacityAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`opacity expected to be basetypes.NumberValue, was: %T`, opacityAttribute))
	}

	selectedAttribute, ok := attributes["selected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`selected is missing from object`)

		return NewDataValueUnknown(), diags
	}

	selectedVal, ok := selectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`selected expected to be basetypes.BoolValue, was: %T`, selectedAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	tiltAttribute, ok := attributes["tilt"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tilt is missing from object`)

		return NewDataValueUnknown(), diags
	}

	tiltVal, ok := tiltAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tilt expected to be basetypes.Int64Value, was: %T`, tiltAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewDataValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	unitAttribute, ok := attributes["unit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	unitVal, ok := unitAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unit expected to be basetypes.StringValue, was: %T`, unitAttribute))
	}

	uppAttribute, ok := attributes["upp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`upp is missing from object`)

		return NewDataValueUnknown(), diags
	}

	uppVal, ok := uppAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`upp expected to be basetypes.NumberValue, was: %T`, uppAttribute))
	}

	zoomAttribute, ok := attributes["zoom"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zoom is missing from object`)

		return NewDataValueUnknown(), diags
	}

	zoomVal, ok := zoomAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zoom expected to be basetypes.Int64Value, was: %T`, zoomAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Id:           idVal,
		AttrHidden:   attrHiddenVal,
		AttrHiddenId: attrHiddenIdVal,
		AttrNoDelete: attrNoDeleteVal,
		AttrNoEdit:   attrNoEditVal,
		Lat:          latVal,
		Lng:          lngVal,
		MapTypeId:    mapTypeIdVal,
		Name:         nameVal,
		OffsetLeft:   offsetLeftVal,
		OffsetTop:    offsetTopVal,
		Opacity:      opacityVal,
		Selected:     selectedVal,
		SiteId:       siteIdVal,
		Tilt:         tiltVal,
		DataType:     typeVal,
		Unit:         unitVal,
		Upp:          uppVal,
		Zoom:         zoomVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Id           basetypes.StringValue `tfsdk:"_id"`
	AttrHidden   basetypes.BoolValue   `tfsdk:"attr_hidden"`
	AttrHiddenId basetypes.StringValue `tfsdk:"attr_hidden_id"`
	AttrNoDelete basetypes.BoolValue   `tfsdk:"attr_no_delete"`
	AttrNoEdit   basetypes.BoolValue   `tfsdk:"attr_no_edit"`
	Lat          basetypes.StringValue `tfsdk:"lat"`
	Lng          basetypes.StringValue `tfsdk:"lng"`
	MapTypeId    basetypes.StringValue `tfsdk:"map_type_id"`
	Name         basetypes.StringValue `tfsdk:"name"`
	OffsetLeft   basetypes.NumberValue `tfsdk:"offset_left"`
	OffsetTop    basetypes.NumberValue `tfsdk:"offset_top"`
	Opacity      basetypes.NumberValue `tfsdk:"opacity"`
	Selected     basetypes.BoolValue   `tfsdk:"selected"`
	SiteId       basetypes.StringValue `tfsdk:"site_id"`
	Tilt         basetypes.Int64Value  `tfsdk:"tilt"`
	DataType     basetypes.StringValue `tfsdk:"type"`
	Unit         basetypes.StringValue `tfsdk:"unit"`
	Upp          basetypes.NumberValue `tfsdk:"upp"`
	Zoom         basetypes.Int64Value  `tfsdk:"zoom"`
	state        attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 19)

	var val tftypes.Value
	var err error

	attrTypes["_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_hidden"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_hidden_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_no_delete"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_no_edit"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["lat"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["lng"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["map_type_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["offset_left"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["offset_top"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["opacity"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["selected"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["site_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tilt"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["unit"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["upp"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["zoom"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 19)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_id"] = val

		val, err = v.AttrHidden.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden"] = val

		val, err = v.AttrHiddenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden_id"] = val

		val, err = v.AttrNoDelete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_delete"] = val

		val, err = v.AttrNoEdit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_edit"] = val

		val, err = v.Lat.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lat"] = val

		val, err = v.Lng.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lng"] = val

		val, err = v.MapTypeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["map_type_id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OffsetLeft.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["offset_left"] = val

		val, err = v.OffsetTop.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["offset_top"] = val

		val, err = v.Opacity.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["opacity"] = val

		val, err = v.Selected.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["selected"] = val

		val, err = v.SiteId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site_id"] = val

		val, err = v.Tilt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tilt"] = val

		val, err = v.DataType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		val, err = v.Unit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["unit"] = val

		val, err = v.Upp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["upp"] = val

		val, err = v.Zoom.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zoom"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"lat":            basetypes.StringType{},
		"lng":            basetypes.StringType{},
		"map_type_id":    basetypes.StringType{},
		"name":           basetypes.StringType{},
		"offset_left":    basetypes.NumberType{},
		"offset_top":     basetypes.NumberType{},
		"opacity":        basetypes.NumberType{},
		"selected":       basetypes.BoolType{},
		"site_id":        basetypes.StringType{},
		"tilt":           basetypes.Int64Type{},
		"type":           basetypes.StringType{},
		"unit":           basetypes.StringType{},
		"upp":            basetypes.NumberType{},
		"zoom":           basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_id":            v.Id,
			"attr_hidden":    v.AttrHidden,
			"attr_hidden_id": v.AttrHiddenId,
			"attr_no_delete": v.AttrNoDelete,
			"attr_no_edit":   v.AttrNoEdit,
			"lat":            v.Lat,
			"lng":            v.Lng,
			"map_type_id":    v.MapTypeId,
			"name":           v.Name,
			"offset_left":    v.OffsetLeft,
			"offset_top":     v.OffsetTop,
			"opacity":        v.Opacity,
			"selected":       v.Selected,
			"site_id":        v.SiteId,
			"tilt":           v.Tilt,
			"type":           v.DataType,
			"unit":           v.Unit,
			"upp":            v.Upp,
			"zoom":           v.Zoom,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.AttrHidden.Equal(other.AttrHidden) {
		return false
	}

	if !v.AttrHiddenId.Equal(other.AttrHiddenId) {
		return false
	}

	if !v.AttrNoDelete.Equal(other.AttrNoDelete) {
		return false
	}

	if !v.AttrNoEdit.Equal(other.AttrNoEdit) {
		return false
	}

	if !v.Lat.Equal(other.Lat) {
		return false
	}

	if !v.Lng.Equal(other.Lng) {
		return false
	}

	if !v.MapTypeId.Equal(other.MapTypeId) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OffsetLeft.Equal(other.OffsetLeft) {
		return false
	}

	if !v.OffsetTop.Equal(other.OffsetTop) {
		return false
	}

	if !v.Opacity.Equal(other.Opacity) {
		return false
	}

	if !v.Selected.Equal(other.Selected) {
		return false
	}

	if !v.SiteId.Equal(other.SiteId) {
		return false
	}

	if !v.Tilt.Equal(other.Tilt) {
		return false
	}

	if !v.DataType.Equal(other.DataType) {
		return false
	}

	if !v.Unit.Equal(other.Unit) {
		return false
	}

	if !v.Upp.Equal(other.Upp) {
		return false
	}

	if !v.Zoom.Equal(other.Zoom) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"lat":            basetypes.StringType{},
		"lng":            basetypes.StringType{},
		"map_type_id":    basetypes.StringType{},
		"name":           basetypes.StringType{},
		"offset_left":    basetypes.NumberType{},
		"offset_top":     basetypes.NumberType{},
		"opacity":        basetypes.NumberType{},
		"selected":       basetypes.BoolType{},
		"site_id":        basetypes.StringType{},
		"tilt":           basetypes.Int64Type{},
		"type":           basetypes.StringType{},
		"unit":           basetypes.StringType{},
		"upp":            basetypes.NumberType{},
		"zoom":           basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = MetaType{}

type MetaType struct {
	basetypes.ObjectType
}

func (t MetaType) Equal(o attr.Type) bool {
	other, ok := o.(MetaType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetaType) String() string {
	return "MetaType"
}

func (t MetaType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return nil, diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueNull() MetaValue {
	return MetaValue{
		state: attr.ValueStateNull,
	}
}

func NewMetaValueUnknown() MetaValue {
	return MetaValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetaValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetaValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetaValue Attribute Value",
				"While creating a MetaValue value, a missing attribute value was detected. "+
					"A MetaValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetaValue Attribute Type",
				"While creating a MetaValue value, an invalid attribute value was detected. "+
					"A MetaValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetaValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetaValue Attribute Value",
				"While creating a MetaValue value, an extra attribute value was detected. "+
					"A MetaValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetaValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetaValue {
	object, diags := NewMetaValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetaValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetaType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetaValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetaValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetaValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetaValueMust(MetaValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetaType) ValueType(ctx context.Context) attr.Value {
	return MetaValue{}
}

var _ basetypes.ObjectValuable = MetaValue{}

type MetaValue struct {
	Msg   basetypes.StringValue `tfsdk:"msg"`
	Rc    basetypes.StringValue `tfsdk:"rc"`
	state attr.ValueState
}

func (v MetaValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rc"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.Rc.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rc"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetaValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetaValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetaValue) String() string {
	return "MetaValue"
}

func (v MetaValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"msg": v.Msg,
			"rc":  v.Rc,
		})

	return objVal, diags
}

func (v MetaValue) Equal(o attr.Value) bool {
	other, ok := o.(MetaValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.Rc.Equal(other.Rc) {
		return false
	}

	return true
}

func (v MetaValue) Type(ctx context.Context) attr.Type {
	return MetaType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetaValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}
}
