// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SpatialRecordDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_hidden": schema.BoolAttribute{
							Computed: true,
						},
						"attr_hidden_id": schema.StringAttribute{
							Computed: true,
						},
						"attr_no_delete": schema.BoolAttribute{
							Computed: true,
						},
						"attr_no_edit": schema.BoolAttribute{
							Computed: true,
						},
						"devices": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"mac": schema.StringAttribute{
										Computed: true,
									},
									"position": schema.SingleNestedAttribute{
										Attributes: map[string]schema.Attribute{
											"x": schema.NumberAttribute{
												Computed: true,
											},
											"y": schema.NumberAttribute{
												Computed: true,
											},
											"z": schema.NumberAttribute{
												Computed: true,
											},
										},
										CustomType: PositionType{
											ObjectType: types.ObjectType{
												AttrTypes: PositionValue{}.AttributeTypes(ctx),
											},
										},
										Computed: true,
									},
								},
								CustomType: DevicesType{
									ObjectType: types.ObjectType{
										AttrTypes: DevicesValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"site_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"meta": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"msg": schema.StringAttribute{
						Computed: true,
					},
					"rc": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetaType{
					ObjectType: types.ObjectType{
						AttrTypes: MetaValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type SpatialRecordModel struct {
	Data types.List   `tfsdk:"data"`
	Id   types.String `tfsdk:"id"`
	Meta MetaValue    `tfsdk:"meta"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return nil, diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return nil, diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return nil, diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return nil, diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	devicesAttribute, ok := attributes["devices"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`devices is missing from object`)

		return nil, diags
	}

	devicesVal, ok := devicesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`devices expected to be basetypes.ListValue, was: %T`, devicesAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return nil, diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Id:           idVal,
		AttrHidden:   attrHiddenVal,
		AttrHiddenId: attrHiddenIdVal,
		AttrNoDelete: attrNoDeleteVal,
		AttrNoEdit:   attrNoEditVal,
		Devices:      devicesVal,
		Name:         nameVal,
		SiteId:       siteIdVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	idAttribute, ok := attributes["_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	attrHiddenAttribute, ok := attributes["attr_hidden"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenVal, ok := attrHiddenAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden expected to be basetypes.BoolValue, was: %T`, attrHiddenAttribute))
	}

	attrHiddenIdAttribute, ok := attributes["attr_hidden_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_hidden_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrHiddenIdVal, ok := attrHiddenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_hidden_id expected to be basetypes.StringValue, was: %T`, attrHiddenIdAttribute))
	}

	attrNoDeleteAttribute, ok := attributes["attr_no_delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_delete is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoDeleteVal, ok := attrNoDeleteAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_delete expected to be basetypes.BoolValue, was: %T`, attrNoDeleteAttribute))
	}

	attrNoEditAttribute, ok := attributes["attr_no_edit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attr_no_edit is missing from object`)

		return NewDataValueUnknown(), diags
	}

	attrNoEditVal, ok := attrNoEditAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attr_no_edit expected to be basetypes.BoolValue, was: %T`, attrNoEditAttribute))
	}

	devicesAttribute, ok := attributes["devices"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`devices is missing from object`)

		return NewDataValueUnknown(), diags
	}

	devicesVal, ok := devicesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`devices expected to be basetypes.ListValue, was: %T`, devicesAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	siteIdAttribute, ok := attributes["site_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site_id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	siteIdVal, ok := siteIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site_id expected to be basetypes.StringValue, was: %T`, siteIdAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Id:           idVal,
		AttrHidden:   attrHiddenVal,
		AttrHiddenId: attrHiddenIdVal,
		AttrNoDelete: attrNoDeleteVal,
		AttrNoEdit:   attrNoEditVal,
		Devices:      devicesVal,
		Name:         nameVal,
		SiteId:       siteIdVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Id           basetypes.StringValue `tfsdk:"_id"`
	AttrHidden   basetypes.BoolValue   `tfsdk:"attr_hidden"`
	AttrHiddenId basetypes.StringValue `tfsdk:"attr_hidden_id"`
	AttrNoDelete basetypes.BoolValue   `tfsdk:"attr_no_delete"`
	AttrNoEdit   basetypes.BoolValue   `tfsdk:"attr_no_edit"`
	Devices      basetypes.ListValue   `tfsdk:"devices"`
	Name         basetypes.StringValue `tfsdk:"name"`
	SiteId       basetypes.StringValue `tfsdk:"site_id"`
	state        attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_hidden"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_hidden_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["attr_no_delete"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["attr_no_edit"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["devices"] = basetypes.ListType{
		ElemType: DevicesValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["site_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_id"] = val

		val, err = v.AttrHidden.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden"] = val

		val, err = v.AttrHiddenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_hidden_id"] = val

		val, err = v.AttrNoDelete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_delete"] = val

		val, err = v.AttrNoEdit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attr_no_edit"] = val

		val, err = v.Devices.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["devices"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.SiteId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	devices := types.ListValueMust(
		DevicesType{
			basetypes.ObjectType{
				AttrTypes: DevicesValue{}.AttributeTypes(ctx),
			},
		},
		v.Devices.Elements(),
	)

	if v.Devices.IsNull() {
		devices = types.ListNull(
			DevicesType{
				basetypes.ObjectType{
					AttrTypes: DevicesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Devices.IsUnknown() {
		devices = types.ListUnknown(
			DevicesType{
				basetypes.ObjectType{
					AttrTypes: DevicesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"devices": basetypes.ListType{
			ElemType: DevicesValue{}.Type(ctx),
		},
		"name":    basetypes.StringType{},
		"site_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_id":            v.Id,
			"attr_hidden":    v.AttrHidden,
			"attr_hidden_id": v.AttrHiddenId,
			"attr_no_delete": v.AttrNoDelete,
			"attr_no_edit":   v.AttrNoEdit,
			"devices":        devices,
			"name":           v.Name,
			"site_id":        v.SiteId,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.AttrHidden.Equal(other.AttrHidden) {
		return false
	}

	if !v.AttrHiddenId.Equal(other.AttrHiddenId) {
		return false
	}

	if !v.AttrNoDelete.Equal(other.AttrNoDelete) {
		return false
	}

	if !v.AttrNoEdit.Equal(other.AttrNoEdit) {
		return false
	}

	if !v.Devices.Equal(other.Devices) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.SiteId.Equal(other.SiteId) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_id":            basetypes.StringType{},
		"attr_hidden":    basetypes.BoolType{},
		"attr_hidden_id": basetypes.StringType{},
		"attr_no_delete": basetypes.BoolType{},
		"attr_no_edit":   basetypes.BoolType{},
		"devices": basetypes.ListType{
			ElemType: DevicesValue{}.Type(ctx),
		},
		"name":    basetypes.StringType{},
		"site_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DevicesType{}

type DevicesType struct {
	basetypes.ObjectType
}

func (t DevicesType) Equal(o attr.Type) bool {
	other, ok := o.(DevicesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DevicesType) String() string {
	return "DevicesType"
}

func (t DevicesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	macAttribute, ok := attributes["mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mac is missing from object`)

		return nil, diags
	}

	macVal, ok := macAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mac expected to be basetypes.StringValue, was: %T`, macAttribute))
	}

	positionAttribute, ok := attributes["position"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`position is missing from object`)

		return nil, diags
	}

	positionVal, ok := positionAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`position expected to be basetypes.ObjectValue, was: %T`, positionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DevicesValue{
		Mac:      macVal,
		Position: positionVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewDevicesValueNull() DevicesValue {
	return DevicesValue{
		state: attr.ValueStateNull,
	}
}

func NewDevicesValueUnknown() DevicesValue {
	return DevicesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDevicesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DevicesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DevicesValue Attribute Value",
				"While creating a DevicesValue value, a missing attribute value was detected. "+
					"A DevicesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DevicesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DevicesValue Attribute Type",
				"While creating a DevicesValue value, an invalid attribute value was detected. "+
					"A DevicesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DevicesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DevicesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DevicesValue Attribute Value",
				"While creating a DevicesValue value, an extra attribute value was detected. "+
					"A DevicesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DevicesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDevicesValueUnknown(), diags
	}

	macAttribute, ok := attributes["mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mac is missing from object`)

		return NewDevicesValueUnknown(), diags
	}

	macVal, ok := macAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mac expected to be basetypes.StringValue, was: %T`, macAttribute))
	}

	positionAttribute, ok := attributes["position"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`position is missing from object`)

		return NewDevicesValueUnknown(), diags
	}

	positionVal, ok := positionAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`position expected to be basetypes.ObjectValue, was: %T`, positionAttribute))
	}

	if diags.HasError() {
		return NewDevicesValueUnknown(), diags
	}

	return DevicesValue{
		Mac:      macVal,
		Position: positionVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewDevicesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DevicesValue {
	object, diags := NewDevicesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDevicesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DevicesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDevicesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDevicesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDevicesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDevicesValueMust(DevicesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DevicesType) ValueType(ctx context.Context) attr.Value {
	return DevicesValue{}
}

var _ basetypes.ObjectValuable = DevicesValue{}

type DevicesValue struct {
	Mac      basetypes.StringValue `tfsdk:"mac"`
	Position basetypes.ObjectValue `tfsdk:"position"`
	state    attr.ValueState
}

func (v DevicesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["mac"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["position"] = basetypes.ObjectType{
		AttrTypes: PositionValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Mac.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["mac"] = val

		val, err = v.Position.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["position"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DevicesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DevicesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DevicesValue) String() string {
	return "DevicesValue"
}

func (v DevicesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var position basetypes.ObjectValue

	if v.Position.IsNull() {
		position = types.ObjectNull(
			PositionValue{}.AttributeTypes(ctx),
		)
	}

	if v.Position.IsUnknown() {
		position = types.ObjectUnknown(
			PositionValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Position.IsNull() && !v.Position.IsUnknown() {
		position = types.ObjectValueMust(
			PositionValue{}.AttributeTypes(ctx),
			v.Position.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"mac": basetypes.StringType{},
		"position": basetypes.ObjectType{
			AttrTypes: PositionValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"mac":      v.Mac,
			"position": position,
		})

	return objVal, diags
}

func (v DevicesValue) Equal(o attr.Value) bool {
	other, ok := o.(DevicesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Mac.Equal(other.Mac) {
		return false
	}

	if !v.Position.Equal(other.Position) {
		return false
	}

	return true
}

func (v DevicesValue) Type(ctx context.Context) attr.Type {
	return DevicesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DevicesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"mac": basetypes.StringType{},
		"position": basetypes.ObjectType{
			AttrTypes: PositionValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = PositionType{}

type PositionType struct {
	basetypes.ObjectType
}

func (t PositionType) Equal(o attr.Type) bool {
	other, ok := o.(PositionType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PositionType) String() string {
	return "PositionType"
}

func (t PositionType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return nil, diags
	}

	xVal, ok := xAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be basetypes.NumberValue, was: %T`, xAttribute))
	}

	yAttribute, ok := attributes["y"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`y is missing from object`)

		return nil, diags
	}

	yVal, ok := yAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`y expected to be basetypes.NumberValue, was: %T`, yAttribute))
	}

	zAttribute, ok := attributes["z"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`z is missing from object`)

		return nil, diags
	}

	zVal, ok := zAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`z expected to be basetypes.NumberValue, was: %T`, zAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PositionValue{
		X:     xVal,
		Y:     yVal,
		Z:     zVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewPositionValueNull() PositionValue {
	return PositionValue{
		state: attr.ValueStateNull,
	}
}

func NewPositionValueUnknown() PositionValue {
	return PositionValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPositionValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PositionValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PositionValue Attribute Value",
				"While creating a PositionValue value, a missing attribute value was detected. "+
					"A PositionValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PositionValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PositionValue Attribute Type",
				"While creating a PositionValue value, an invalid attribute value was detected. "+
					"A PositionValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PositionValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PositionValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PositionValue Attribute Value",
				"While creating a PositionValue value, an extra attribute value was detected. "+
					"A PositionValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PositionValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPositionValueUnknown(), diags
	}

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return NewPositionValueUnknown(), diags
	}

	xVal, ok := xAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be basetypes.NumberValue, was: %T`, xAttribute))
	}

	yAttribute, ok := attributes["y"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`y is missing from object`)

		return NewPositionValueUnknown(), diags
	}

	yVal, ok := yAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`y expected to be basetypes.NumberValue, was: %T`, yAttribute))
	}

	zAttribute, ok := attributes["z"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`z is missing from object`)

		return NewPositionValueUnknown(), diags
	}

	zVal, ok := zAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`z expected to be basetypes.NumberValue, was: %T`, zAttribute))
	}

	if diags.HasError() {
		return NewPositionValueUnknown(), diags
	}

	return PositionValue{
		X:     xVal,
		Y:     yVal,
		Z:     zVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewPositionValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PositionValue {
	object, diags := NewPositionValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPositionValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PositionType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPositionValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPositionValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPositionValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPositionValueMust(PositionValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PositionType) ValueType(ctx context.Context) attr.Value {
	return PositionValue{}
}

var _ basetypes.ObjectValuable = PositionValue{}

type PositionValue struct {
	X     basetypes.NumberValue `tfsdk:"x"`
	Y     basetypes.NumberValue `tfsdk:"y"`
	Z     basetypes.NumberValue `tfsdk:"z"`
	state attr.ValueState
}

func (v PositionValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["x"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["y"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["z"] = basetypes.NumberType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.X.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["x"] = val

		val, err = v.Y.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["y"] = val

		val, err = v.Z.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["z"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PositionValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PositionValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PositionValue) String() string {
	return "PositionValue"
}

func (v PositionValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"x": basetypes.NumberType{},
		"y": basetypes.NumberType{},
		"z": basetypes.NumberType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"x": v.X,
			"y": v.Y,
			"z": v.Z,
		})

	return objVal, diags
}

func (v PositionValue) Equal(o attr.Value) bool {
	other, ok := o.(PositionValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.X.Equal(other.X) {
		return false
	}

	if !v.Y.Equal(other.Y) {
		return false
	}

	if !v.Z.Equal(other.Z) {
		return false
	}

	return true
}

func (v PositionValue) Type(ctx context.Context) attr.Type {
	return PositionType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PositionValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"x": basetypes.NumberType{},
		"y": basetypes.NumberType{},
		"z": basetypes.NumberType{},
	}
}

var _ basetypes.ObjectTypable = MetaType{}

type MetaType struct {
	basetypes.ObjectType
}

func (t MetaType) Equal(o attr.Type) bool {
	other, ok := o.(MetaType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetaType) String() string {
	return "MetaType"
}

func (t MetaType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return nil, diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueNull() MetaValue {
	return MetaValue{
		state: attr.ValueStateNull,
	}
}

func NewMetaValueUnknown() MetaValue {
	return MetaValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetaValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetaValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetaValue Attribute Value",
				"While creating a MetaValue value, a missing attribute value was detected. "+
					"A MetaValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetaValue Attribute Type",
				"While creating a MetaValue value, an invalid attribute value was detected. "+
					"A MetaValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetaValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetaValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetaValue Attribute Value",
				"While creating a MetaValue value, an extra attribute value was detected. "+
					"A MetaValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetaValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	rcAttribute, ok := attributes["rc"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rc is missing from object`)

		return NewMetaValueUnknown(), diags
	}

	rcVal, ok := rcAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rc expected to be basetypes.StringValue, was: %T`, rcAttribute))
	}

	if diags.HasError() {
		return NewMetaValueUnknown(), diags
	}

	return MetaValue{
		Msg:   msgVal,
		Rc:    rcVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetaValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetaValue {
	object, diags := NewMetaValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetaValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetaType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetaValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetaValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetaValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetaValueMust(MetaValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetaType) ValueType(ctx context.Context) attr.Value {
	return MetaValue{}
}

var _ basetypes.ObjectValuable = MetaValue{}

type MetaValue struct {
	Msg   basetypes.StringValue `tfsdk:"msg"`
	Rc    basetypes.StringValue `tfsdk:"rc"`
	state attr.ValueState
}

func (v MetaValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rc"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.Rc.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rc"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetaValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetaValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetaValue) String() string {
	return "MetaValue"
}

func (v MetaValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"msg": v.Msg,
			"rc":  v.Rc,
		})

	return objVal, diags
}

func (v MetaValue) Equal(o attr.Value) bool {
	other, ok := o.(MetaValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.Rc.Equal(other.Rc) {
		return false
	}

	return true
}

func (v MetaValue) Type(ctx context.Context) attr.Type {
	return MetaType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetaValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"msg": basetypes.StringType{},
		"rc":  basetypes.StringType{},
	}
}
